### ISSUE TITLE
v2ray是否需要修改？

### ISSUE THREAD

**Issue by SouHong** [chongshengB/rt-n56u#1]
我没有测试，估计大神还在完善中。
shadowsocks.sh
其中：
stype=`nvram get ssp_type_x$1`
  echo $stype
    if [ "$stype" == "ss" ] ;then
        sscmd="ss-redir"
       elif [ "$stype" == "ssr" ] ;then
        sscmd="ssr-redir"
       elif [ "$stype" == "v2ray" ] ;then
        sscmd="v2ray"
    fi
	UDP_RELAY_SERVER=$(nvram get udp_relay_server)
	utype=`nvram get ssp_type_x$UDP_RELAY_SERVER`
    if [ "$utype" == "ss" ] ;then
        ucmd="ss-redir"
       elif [ "$utype" == "ssr" ] ;then
        ucmd="ssr-redir"
       elif [ "$utype" == "v2ray" ] ;then
        ucmd="v2ray"
fi
sscmd="v2ray"
ucmd="v2ray"
="v2ray"是否需要改成 ="/tmp/v2ray"

elif [ "$utype" == "v2ray" ] ; then
        lua /usr/share/shadowsocksr/genv2config.lua $UDP_RELAY_SERVER udp $(uci_get_by_name $UDP_RELAY_SERVER local_port) > /var/etc/v2-ssr-reudp.json
        sed -i 's/\\//g' /var/etc/v2-ssr-reudp.json
        $ucmd -config /var/etc/v2-ssr-reudp.json >/dev/null 2>&1 &   
fi
lua /usr/share/shadowsocksr/genv2config.lua.......
是否支持lua；路径？

boot() {
	(/usr/share/shadowsocksr/chinaipset.sh && sleep 5 && start >/dev/null 2>&1) &
}
这段是否要保留？应该不影响使用。

启动pdnsd服务端口使用5335：
server_port = 5335;
https://cokebar.github.io/gfwlist2dnsmasq/dnsmasq_gfwlist_ipset.conf文件中使用的 #5353 端口
可否使用https://cokebar.github.io/gfwlist2dnsmasq/gfwlist_domain.txt这个文件
sed '/.*/s/.*/server=\/\.&\/127.0.0.1#5335\nipset=\/\.&\/gfwlist/' /tmp/gfwlist_domain.txt >/etc/storage/gfwlist/dnsmasq_gfwlist_ipset.conf
或者
server_port = 5353;
server {
	label= "ssr-pdnsd";
	ip = $tcp_dns_list;
	port = 5353;
	timeout=6;
	uptest=none;
	interval=10m;
	purge_cache=off;
}
port = 443;

端口修改为5353：
[shadowsocks.zip](https://github.com/chongshengB/rt-n56u/files/3953544/shadowsocks.zip)

---------------------------------------------------------------------------------------------------------
修改为5335需要添加 cmp ：
[update_gfwlist.zip](https://github.com/chongshengB/rt-n56u/files/3953584/update_gfwlist.zip)

添加CMP：修改了381行：# CONFIG_CMP is not set 改为 CONFIG_CMP=y
[busybox.zip](https://github.com/chongshengB/rt-n56u/files/3953599/busybox.zip)
----------------------------------------------------------------------------------------------------------

**Comment by SouHong** [comment]
ssr-monitor
39行:
server=`cat /etc/ssr_ip`

server=`cat /etc/storage/ssr_ip`

**Comment by chongshengB** [comment]
已修正，感谢指导
