### ISSUE TITLE
开启55r会出现这样的错误提示，不知道什么原因

### ISSUE THREAD

**Issue by jing10837** [chongshengB/rt-n56u#10]
Dec 23 22:40:18 SS: 启动成功。
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zzux.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zzcloud.me 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zzcartoon.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zyzc9.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zyns.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zynamics.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zynaima.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zvereff.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zuola.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zuo.la 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zuobiao.me 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zsrhao.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zspeeder.me 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zpn.im 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zozotown.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zorrovpn.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zoozle.net 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zootool.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zoogvpn.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.net 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zonaeuropa.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zomobo.net 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zodgame.us 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zmw.cn 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zkaip.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zippyshare.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain ziporn.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zinio.com 
Dec 23 22:40:18 dnsmasq[2244]: using nameserver 127.0.0.1#5353 for domain zim.vn 
Dec 23 22:40:18 dnsmasq[2244]: using 5672 more nameservers
Dec 23 22:41:21 ssr-redir[2094]: client_post_decrypt
Dec 23 22:41:21 ssr-redir[2094]: invalid password or cipher
Dec 23 22:41:22 ssr-redir[2094]: invalid password or cipher

密码应该是没问题的，很奇怪

**Comment by chongshengB** [comment]
已修复，等待推送
