### ISSUE TITLE
能不能添加腾讯云DDNS

### ISSUE THREAD

**Issue by shine1000** [chongshengB/rt-n56u#103]
能不能添加腾讯云DDNS 谢谢了

**Comment by Avantyjw** [comment]
我也求这个

**Comment by SenLief** [comment]
自己用脚本跑就是了。

**Comment by Avantyjw** [comment]
> 自己用脚本跑就是了。

百度了一圈没找到脚本

**Comment by SenLief** [comment]
github上就有啊，不要搜腾讯云ddns，搜dnspod ddns shell脚本就可以了。添加定时任务即可

发自我的华为手机


-------- 原始邮件 --------
发件人： Avantyjw <notifications@github.com>
日期： 2020年3月28日周六 上午10:27
收件人： chongshengB/rt-n56u <rt-n56u@noreply.github.com>
抄送： SenLief <zjanence@gmail.com>, Comment <comment@noreply.github.com>
主 题： Re: [chongshengB/rt-n56u] 能不能添加腾讯云DDNS (#103)

自己用脚本跑就是了。

百度了一圈没找到脚本

―

**Comment by Avantyjw** [comment]
> github上就有啊，不要搜腾讯云ddns，搜dnspod ddns shell脚本就可以了。添加定时任务即可 发自我的华为手机
> […](#)
> -------- 原始邮件 -------- 发件人： Avantyjw <notifications@github.com> 日期： 2020年3月28日周六 上午10:27 收件人： chongshengB/rt-n56u <rt-n56u@noreply.github.com> 抄送： SenLief <zjanence@gmail.com>, Comment <comment@noreply.github.com> 主 题： Re: [chongshengB/rt-n56u] 能不能添加腾讯云DDNS (#103) 自己用脚本跑就是了。 百度了一圈没找到脚本 ― You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FchongshengB%2Frt-n56u%2Fissues%2F103%23issuecomment-605382358&data=02%7C01%7C%7Caffba38e6e794650af1b08d7d2bf960f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637209592603933053&sdata=Yz6VcyreO99cLHCcVq6uB1XBjjEygYgRWqyinIsDLpU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHT6YA4P42NYM3DVJW4JVKDRJVOBRANCNFSM4LDY7Q3A&data=02%7C01%7C%7Caffba38e6e794650af1b08d7d2bf960f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637209592603933053&sdata=fRg55wO3xxBp9XMJmlvptJnBt7OhfvZqOYpkOCoXs1c%3D&reserved=0>.

感谢 我研究一下

**Comment by huierwsh** [comment]
哈哈，我也想要这个功能，图形界面方便
