### ISSUE TITLE
固件的建议

### ISSUE THREAD

**Issue by zshytkd2** [chongshengB/rt-n56u#109]
1.Newifi3，K2pA1 科学上网的订阅地址重启（含断电后）会消失，保存不到
2.科学上网可否自动定时检查订阅地址的有效性，自动切换到有效地址，不用每天入路由设置

另外，这是我到现在为止，用过最好的固件，谢谢作者，努力加油，期待你的新作

**Comment by chongshengB** [comment]
目前正在重做科学上网...订阅应该会比目前的好用一点，感谢您的建议
