### ISSUE TITLE
似乎是没有openvpn？

### ISSUE THREAD

**Issue by zlylong** [chongshengB/rt-n56u#11]
我自己编译似乎也没有找到这个服务？

**Comment by yuaiwu** [comment]
CONFIG_FIRMWARE_INCLUDE_OPENVPN=y
CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y
就有吧

**Comment by nianqing126** [comment]
> CONFIG_FIRMWARE_INCLUDE_OPENVPN=y
> CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y
> 就有吧

这样不行，还是没有op协议
