### ISSUE TITLE
编译最新版的源码，hosts规则会下载失败，感觉可能是更新openssl之后wget的https出问题了

### ISSUE THREAD

**Issue by icy37785** [chongshengB/rt-n56u#113]
Mar 12 03:34:24 adbyby: 保存adbyby防火墙规则成功！
Mar 12 03:34:24 adbyby: 正在下载: https://cdn.jsdelivr.net/gh/vokins/yhosts/hosts
Mar 12 03:34:24 adbyby: https://cdn.jsdelivr.net/gh/vokins/yhosts/hosts 下载失败！
Mar 12 03:34:24 adbyby: 正在下载: https://dev.tencent.com/u/shaoxia1991/p/yhosts/git/raw/master/data/tvbox.txt
Mar 12 03:34:24 adbyby: https://dev.tencent.com/u/shaoxia1991/p/yhosts/git/raw/master/data/tvbox.txt 下载失败！
Mar 12 03:34:24 adbyby: 正在对hosts文件进行去重处理.

**Comment by icy37785** [comment]
确定是openssl的问题了
wget: can't execute 'openssl': No such file or directory
受影响的不止wget受到了影响
curl也受到了影响

**Comment by MeIsReallyBa** [comment]
Mar 12 20:24:49 adbyby: 正在下载: https://cdn.jsdelivr.net/gh/vokins/yhosts/hosts
Mar 12 20:24:49 adbyby: hosts下载成功,处理中...
Mar 12 20:24:49 adbyby: 正在下载: https://dev.tencent.com/u/shaoxia1991/p/yhosts/git/raw/master/data/tvbox.txt
Mar 12 20:24:50 adbyby: hosts下载成功,处理中...
Mar 12 20:24:50 adbyby: 正在对hosts文件进行去重处理.
正常的啊，自己clean下重新编译吧。

**Comment by MeIsReallyBa** [comment]
K2P:/home/root # wget  https://dev.tencent.com/u/shaoxia1991/p/yhosts/git/raw/ma
ster/data/tvbox.txt
Connecting to dev.tencent.com (115.159.21.113:443)
tvbox.txt            100% |*******************************|  3876   0:00:00 ETA

手动执行wget。

**Comment by icy37785** [comment]
> K2P:/home/root # wget https://dev.tencent.com/u/shaoxia1991/p/yhosts/git/raw/ma
> ster/data/tvbox.txt
> Connecting to dev.tencent.com (115.159.21.113:443)
> tvbox.txt 100% |*******************************| 3876 0:00:00 ETA
> 
> 手动执行wget。

我手动执行会报错，真的挺奇怪的。
K2P:/home/root # wget https://raw.githubusercontent.com/vokins/yhosts/master/hosts -O /tmp/adbyby/hosts
Connecting to raw.githubusercontent.com (151.101.112.133:443)
wget: can't execute 'openssl': No such file or directory

我重新编译一下看看QAQ
