### ISSUE TITLE
hiboy固件更新你的固件后，微信推送依然有效，是否可以原生加入

### ISSUE THREAD

**Issue by molun** [chongshengB/rt-n56u#114]
路由器为B70，
1.固件内ssr可以转换成Lean版本或者passwall吗
2.科学上网主备只能选择自定义或者订阅二选一，可否自由选择自己添加的和订阅的

**Comment by MeIsReallyBa** [comment]
老毛子没lua，不是你想移植ssr plus就能随便移植的。

**Comment by ag2s20150909** [comment]
你这是脏刷，hiby固件的软件还存在。

**Comment by kiddy99** [comment]
原则上问题不大，不管是hiboy 还是congshengB 都是基于Hanwckf的源码吗！
