### ISSUE TITLE
请问这些是什么?使用hiboy和hanwckf 固件并没有这些信息 ,能否移除?

### ISSUE THREAD

**Issue by forever2019** [chongshengB/rt-n56u#115]
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zzux.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zzcloud.me 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zzcartoon.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zyzc9.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zyns.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zynamics.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zynaima.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zvereff.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zuola.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zuo.la 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zuobiao.me 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zsrhao.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zspeeder.me 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zpn.im 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zozotown.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zorrovpn.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zoozle.net 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zootool.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zoogvpn.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.net 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zonaeuropa.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zomobo.net 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zodgame.us 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zmw.cn 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zkaip.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zippyshare.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain ziporn.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zinio.com 
Mar 13 09:33:42 dnsmasq[1894]: using nameserver 127.0.0.1#5353 for domain zim.vn

**Comment by chongshengB** [comment]
加载到dnsmasq的gfw列表...
