### ISSUE TITLE
花生壳 问题

### ISSUE THREAD

**Issue by lwi360** [chongshengB/rt-n56u#120]
【花生壳内网版】: 找不到 /opt/bin/oraysl ，需要手动安装 /opt/bin/oraysl
【花生壳内网版】: 找不到 /opt/bin/oraynewph ，需要手动安装 /opt/bin/oraynewph

这个是什么原因呀，我想用花生壳，但是里面没有花生壳的菜单，该怎么安装呢？给个提示呗！谢谢啦！

**Comment by tslwoainil** [comment]
建议老大添加老毛子的花生壳内网版插件，谢谢
