### ISSUE TITLE
希望适配网件R6800

### ISSUE THREAD

**Issue by FenghenHome** [chongshengB/rt-n56u#121]
希望适配网件R6800，6700v2，r6800，r6900v2都是通用的，用户群还是很多的，希望大佬适配
之前无灯适配过，PandoraBox也适配过，链接如下：
https://www.right.com.cn/forum/thread-494214-1-1.html

**Comment by chongshengB** [comment]
方便的话可以加群或者我QQ联系我

**Comment by FenghenHome** [comment]
telegram给你留言了

**Comment by FenghenHome** [comment]
我可以借机器给您，适配完还我就行
