### ISSUE TITLE
fail to compile transmission after upgrading openssl

### ISSUE THREAD

**Issue by HiGarfield** [chongshengB/rt-n56u#123]
In old versions before  upgrading openssl 1.1.1, I can add  transmission by adding following lines to the .config file:
CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=y
CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=y

However, after upgrading openssl 1.1.1, the code fail to compile.

**Comment by chongshengB** [comment]
fixed
