### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by darwin-lu-hotmail** [chongshengB/rt-n56u#124]
web_ex.c:4209:69: error: 'do_applydb_cgi' undeclared here (not in a function); did you mean 'do_apply_cgi'?
  { "applydb.cgi*", "text/html", no_cache_IE7, do_html_post_and_get, do_applydb_cgi, 1 },
                                                                     ^~~~~~~~~~~~~~
                                                                     do_apply_cgi
web_ex.c:4210:66: error: 'do_dbconf' undeclared here (not in a function)
  { "dbconf", "text/javascript", no_cache_IE, do_html_apply_post, do_dbconf, 0 },
                                                                  ^~~~~~~~~
<builtin>: recipe for target 'web_ex.o' failed
make[2]: *** [web_ex.o] Error 1
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/httpd'
Makefile:225: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
Makefile:202: recipe for target 'user_only' failed
make: *** [user_only] Error 2

**Comment by darwin-lu-hotmail** [comment]
Compiling ../libcli/security/security_descriptor.c
../librpc/ndr/ndr_dcerpc.c:31:107: warning: 'struct dcerpc_sec_vt_count' declared inside parameter list will not be visible outside of this definition or declaration
 _PUBLIC_ enum ndr_err_code ndr_push_dcerpc_sec_vt_count(struct ndr_push *ndr, int ndr_flags, const struct dcerpc_sec_vt_count *r)
                                                                                                           ^~~~~~~~~~~~~~~~~~~
../librpc/ndr/ndr_dcerpc.c:38:101: warning: 'struct dcerpc_sec_vt_count' declared inside parameter list will not be visible outside of this definition or declaration
 _PUBLIC_ enum ndr_err_code ndr_pull_dcerpc_sec_vt_count(struct ndr_pull *ndr, int ndr_flags, struct dcerpc_sec_vt_count *r)
                                                                                                     ^~~~~~~~~~~~~~~~~~~
../librpc/ndr/ndr_dcerpc.c: In function 'ndr_pull_dcerpc_sec_vt_count':
../librpc/ndr/ndr_dcerpc.c:48:3: error: dereferencing pointer to incomplete type 'struct dcerpc_sec_vt_count'
  r->count = 0;
   ^~
../librpc/ndr/ndr_dcerpc.c:60:17: error: 'DCERPC_SEC_VT_COMMAND_END' undeclared (first use in this function); did you mean 'DCERPC_SEC_VT_MAGIC'?
   if (command & DCERPC_SEC_VT_COMMAND_END) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                 DCERPC_SEC_VT_MAGIC
../librpc/ndr/ndr_dcerpc.c:60:17: note: each undeclared identifier is reported only once for each function it appears in
../librpc/ndr/ndr_dcerpc.c: At top level:
../librpc/ndr/ndr_dcerpc.c:71:9: warning: 'struct dcerpc_sec_verification_trailer' declared inside parameter list will not be visible outside of this definition or declaration
  struct dcerpc_sec_verification_trailer **_r)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./../lib/util/charset/charset.h:28:0,
                 from ./../lib/util/util.h:24,
                 from include/includes.h:506,
                 from ../librpc/ndr/ndr_dcerpc.c:23:
../librpc/ndr/ndr_dcerpc.c: In function 'ndr_pop_dcerpc_sec_verification_trailer':
../librpc/ndr/ndr_dcerpc.c:83:27: error: invalid application of 'sizeof' to incomplete type 'struct dcerpc_sec_verification_trailer'
  r = talloc_zero(mem_ctx, struct dcerpc_sec_verification_trailer);
                           ^
./../lib/talloc/talloc.h:591:65: note: in definition of macro 'talloc_zero'
 #define talloc_zero(ctx, type) (type *)_talloc_zero(ctx, sizeof(type), #type)
                                                                 ^~~~
../librpc/ndr/ndr_dcerpc.c:100:12: error: 'DCERPC_SEC_VT_MAX_SIZE' undeclared (first use in this function); did you mean 'DCERPC_SEC_VT_MAGIC'?
  if (ofs > DCERPC_SEC_VT_MAX_SIZE) {
            ^~~~~~~~~~~~~~~~~~~~~~
            DCERPC_SEC_VT_MAGIC
../librpc/ndr/ndr_dcerpc.c:142:12: warning: implicit declaration of function 'ndr_pull_dcerpc_sec_verification_trailer'; did you mean 'ndr_pop_dcerpc_sec_verification_trailer'? [-Wimplicit-function-declaration]
  ndr_err = ndr_pull_dcerpc_sec_verification_trailer(sub_ndr,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            ndr_pop_dcerpc_sec_verification_trailer
In file included from include/includes.h:23:0,
                 from ../librpc/ndr/ndr_dcerpc.c:23:
../lib/zlib/../replace/replace.h:725:77: error: dereferencing pointer to incomplete type 'struct dcerpc_sec_verification_trailer'
 #define ZERO_STRUCTP(x) do { if ((x) != NULL) memset((char *)(x), 0, sizeof(*(x))); } while(0)

**Comment by PigodChen** [comment]
似乎是不编译ssp的时候就没有skidbv2导致的错误，改下web_ex.c文件
	{ "applydb.cgi*", "text/html", no_cache_IE7, do_html_post_and_get, do_applydb_cgi, 1 },
	{ "dbconf", "text/javascript", no_cache_IE, do_html_apply_post, do_dbconf, 0 },
改成
#if defined (APP_SHADOWSOCKS)
	{ "applydb.cgi*", "text/html", no_cache_IE7, do_html_post_and_get, do_applydb_cgi, 1 },
	{ "dbconf", "text/javascript", no_cache_IE, do_html_apply_post, do_dbconf, 0 },
#endif
就可以了

**Comment by PigodChen** [comment]
似乎是不编译ssp的时候没有skipdb导致的问题，如果编译ssp就不会出错
可以改下web_ex.c文件

> 	{ "applydb.cgi*", "text/html", no_cache_IE7, do_html_post_and_get, do_applydb_cgi, 1 },
	{ "dbconf", "text/javascript", no_cache_IE, do_html_apply_post, do_dbconf, 0 },

改成

> #if defined (APP_SHADOWSOCKS)
	{ "applydb.cgi*", "text/html", no_cache_IE7, do_html_post_and_get, do_applydb_cgi, 1 },
	{ "dbconf", "text/javascript", no_cache_IE, do_html_apply_post, do_dbconf, 0 },
#endif

就可以了

**Comment by chongshengB** [comment]
已修复不集成ssp编译错误的问题
