### ISSUE TITLE
kumasocks在SSP‘添加节点’选项中找不到了

### ISSUE THREAD

**Issue by ivybridgei** [chongshengB/rt-n56u#125]
编译的时候加入了kumasocks，ipt2socks，编译出来的固件刷入后在SSP添加节点中找不到socks相关的选项。

**Comment by ntgeralt** [comment]
是的，刚试过最新一版OYE预编译固件，socks客户端找不着
另外不明白adbyby默认参数去不了大部分基本广告，反而一启用yhost就去光光

**Comment by ivybridgei** [comment]
> 是的，刚试过最新一版OYE预编译固件，socks客户端找不着
> 另外不明白adbyby默认参数去不了大部分基本广告，反而一启用yhost就去光光



> 是的，刚试过最新一版OYE预编译固件，socks客户端找不着
> 另外不明白adbyby默认参数去不了大部分基本广告，反而一启用yhost就去光光

这个版本bug太多，我已经回退0304版本

**Comment by chongshengB** [comment]
功能会慢慢加回来，kumasocks已添加回来

**Comment by ntgeralt** [comment]
@chongshengB URL添加节点的按钮放在外面的小建议
![Desktop Screenshot 2020 04 01 - 13 55 40 50](https://user-images.githubusercontent.com/8230651/78104038-fd8eef80-7420-11ea-867a-e4a88150d29a.png)
