### ISSUE TITLE
SSP(0319 version) Imported nodes do not display on the UI 

### ISSUE THREAD

**Issue by ag2s20150909** [chongshengB/rt-n56u#127]
SSP(0319 version) Imported nodes do not display on the UI 。
SSP(3月19号的源码)导入的节点在UI上不显示。

**Comment by chongshengB** [comment]
什么类型的节点？

**Comment by ag2s20150909** [comment]
> 什么类型的节点？

手动导入的ssr

![8664jf.png](https://s1.ax1x.com/2020/03/20/8664jf.png)

**Comment by chongshengB** [comment]
ctrl+F5即可或者清除缓存

**Comment by ag2s20150909** [comment]
> ctrl+F5即可或者清除缓存

肯定清除过缓存。重启路由器，重置路由器，都是这样。

**Comment by chongshengB** [comment]
试过开无痕浏览没？
