### ISSUE TITLE
自动编译错误

### ISSUE THREAD

**Issue by xbeyond3** [chongshengB/rt-n56u#128]
我只在自动编译里改了把几个y改成了n，其他的都没有动，每次编译都是错误
web_ex.c:4219:47: note: (near initialization for 'mime_handlers[25].input')
web_ex.c:4219:69: error: 'do_applydb_cgi' undeclared here (not in a function); did you mean 'do_apply_cgi'?
  { "applydb.cgi*", "text/html", no_cache_IE7, do_html_post_and_get, do_applydb_cgi, 1 },
                                                                     ^~~~~~~~~~~~~~
                                                                     do_apply_cgi
web_ex.c:4220:66: error: 'do_dbconf' undeclared here (not in a function)
  { "dbconf", "text/javascript", no_cache_IE, do_html_apply_post, do_dbconf, 0 },
                                                                  ^~~~~~~~~
make[2]: *** [web_ex.o] Error 1
<builtin>: recipe for target 'web_ex.o' failed
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/httpd'
make[1]: *** [all] Error 2
Makefile:224: recipe for target 'all' failed
make: *** [user_only] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
Makefile:202: recipe for target 'user_only' failed
##[error]Process completed with exit code 2.

**Comment by liyufan** [comment]
#124

**Comment by chongshengB** [comment]
已修复不集成ssp编译错误的问题

**Comment by xbeyond3** [comment]
感谢大佬！！已经成功！！
