### ISSUE TITLE
能不能考虑集成个qos的插件

### ISSUE THREAD

**Issue by yuaiwu** [chongshengB/rt-n56u#13]
比如sqm就很好了。padavan缺个qos,感觉是个路由器工能都不完整了。谢谢努力。

**Comment by forever2019** [comment]
Qos智能限速 是目前padavan欠缺的功能 
 其他功能支持都很强大 唯独缺少限速  很遗憾

**Comment by jw10126121** [comment]
sqm如果能加入，就可以妥妥用来当主路由了。。。 可惜
