### ISSUE TITLE
20200319的版本,gfwlist更新失败

### ISSUE THREAD

**Issue by stonereese** [chongshengB/rt-n56u#136]
Mar 21 19:11:40 gfwlist: Starting update...
Mar 21 19:11:47 gfwlist: 列表下载失败,请重试！

下午和晚上都是,运营商是联通网络,已经测试全局走代理,也是不能下载,PC上v2rayN上带的gfwlist地址,可以正常更新,麻烦您测试一下,是否是固件的问题,谢谢.

**Comment by stonereese** [comment]
忘了说，路由器是K2P

**Comment by stonereese** [comment]
再补充一下：gfwlist更新前，使用gfw模式，节点是可以正常使用的，更新失败后，节点在gfw模式下无法使用，路由器重启也不行，重启ss服务后，显示gfw规则有5702条，但在gfw模式下还是无法使用。绕过ip模式，可以正常使用。

**Comment by mzit** [comment]
相同问题+1

**Comment by icy37785** [comment]
> 再补充一下：gfwlist更新前，使用gfw模式，节点是可以正常使用的，更新失败后，节点在gfw模式下无法使用，路由器重启也不行，重启ss服务后，显示gfw规则有5702条，但在gfw模式下还是无法使用。绕过ip模式，可以正常使用。



> 相同问题+1

20号更新的不就是解决这个问题么。。。你们在20号之后的issues不应该呀。

**Comment by iceyheart** [comment]
忘了是不是更新引起的，总之现在GFW模式无法连接，白名单模式则什么DNS都不需要开，默认就可以代理。

**Comment by spiderpigpig** [comment]
gfw模式不能使用+1
