### ISSUE TITLE
开启transmission功能后编译出错.

### ISSUE THREAD

**Issue by xiaole51** [chongshengB/rt-n56u#145]
开启transmission功能后编译出错.
看似是跟新的openssl发生了兼容问题.
请见下面log和配置文件.
logs: https://pastebin.com/1mRWGe8k
config: https://pastebin.com/tBzDqZsk

![Image 058](https://user-images.githubusercontent.com/22991235/77501945-695ae080-6e94-11ea-9449-49f7edf30be5.jpg)

PS: Transmission 的版本能否更新一下,当前版本有些老了.
当前版本: === Transmission 2.90 (2016/02/28) ===

**Comment by fbrav530** [comment]
我出遇到同样问题 ，你解决了吗？

**Comment by chongshengB** [comment]
已修复
