### ISSUE TITLE
请采用此驱动，此驱动测速在newifi3上表现好于目前

### ISSUE THREAD

**Issue by happytrudy** [chongshengB/rt-n56u#148]
https://github.com/trublemaker/mt7603-4.1.2.0

**Comment by xiaole51** [comment]
这个是所谓的鸡血驱动吗?
最好有对比数据提供能得到更多关注.

**Comment by whycoby** [comment]
赞同！此驱动在恩山测试了好长时间了，有很多数据对比的帖子，目前来说这个驱动对D2来说是最稳定好用的，可苦于开发该驱动的作者只做纯净版固件，要是能chonshengB能用些驱动制作固件，绝对大热！原帖：https://www.right.com.cn/forum/thread-2498272-1-1.html
另附该驱动测试贴：https://www.right.com.cn/forum/thread-1658410-1-1.html

**Comment by qpzr** [comment]
hanwckf 源码那边已经更新了  就等这边同步了就开车
scripts: fix build

 master
@hanwckf
hanwckf committed 7 hours ago 
1 parent 05bdd56 commit c386f932b0a63c79113dce268797137a938c132c
Showing  with 3 additions and 0 deletions.
 3  trunk/build_firmware_modify 
@@ -140,6 +140,9 @@ rm -rf "$dir_wifi_dst/mt76x2"
rm -rf "$dir_wifi_dst/mt76x3"
rm -rf "$dir_wifi_dst/mt7628"
rm -rf "$dir_wifi_dst/mt7615"

mkdir -p "$dir_wifi_dst/mt76x3"
cp -f "$dir_wifi_src/rtpci/4.1.X.X/mt76x3/Kconfig" "$dir_wifi_dst/mt76x3/Kconfig"

**Comment by xiaole51** [comment]
今天测试了一下hanwckf 提供的测试包.
2.4G确实有了质的改善.
原来看直播非常卡的现象消失了, 弱信号稳定性也加强.
非常值得倒入.

**Comment by omnjpa27516** [comment]
@chongshengB 今天编译报错就是这个新驱动配置变了导致的，能更新一下 NEWIFI-D1 的配置吗？谢谢。

**Comment by chongshengB** [comment]
已同步了hanwckf的源码
