### ISSUE TITLE
斐讯k2（psg1218）不能开机

### ISSUE THREAD

**Issue by lxl6125** [chongshengB/rt-n56u#15]
斐讯k2（psg1218）不能开机

**Comment by SouHong** [comment]
试过https://c-t.work/s/62b6e4f248a04b这里提供的k2固件了吗？
恩山帖子938楼。

**Comment by lxl6125** [comment]
> 试过[https://c-t.work/s/62b6e4f248a04b这里提供的k2固件了吗？](https://c-t.work/s/62b6e4f248a04b%E8%BF%99%E9%87%8C%E6%8F%90%E4%BE%9B%E7%9A%84k2%E5%9B%BA%E4%BB%B6%E4%BA%86%E5%90%97%EF%BC%9F)
> 恩山帖子938楼。

这个可以用，不过科学上网没有订阅功能吗？

**Comment by SouHong** [comment]
暂时没有

**Comment by sl1n** [comment]
> 试过[https://c-t.work/s/62b6e4f248a04b这里提供的k2固件了吗？](https://c-t.work/s/62b6e4f248a04b%E8%BF%99%E9%87%8C%E6%8F%90%E4%BE%9B%E7%9A%84k2%E5%9B%BA%E4%BB%B6%E4%BA%86%E5%90%97%EF%BC%9F) 恩山帖子938楼。

地址不能访问了，现在编译psg1218,K2还是无法进入后台管理，请问有什么办法吗
