### ISSUE TITLE
k2p的0319版本,2.4Gwifi速度很慢

### ISSUE THREAD

**Issue by stonereese** [chongshengB/rt-n56u#153]
RT,升级到0319后没在意,之后就出差了,这两天回来发现网速很慢,我联通100M宽带,使用speedtest测试,2.4Gwifi只有5M宽带,5Gwifi没有问题,改了多处设置无果,恢复出厂设置后,2.4Gwifi能有30M宽带,但这还与实际不符,刷回0315版本后,2.4Gwifi可以跑到50-80M.

**Comment by stonereese** [comment]
退回0315版本后,gfwlist也可以正常更新了~~

**Comment by chongshengB** [comment]
驱动我没动过，你可以试试最新的
