### ISSUE TITLE
关于filebrowser

### ISSUE THREAD

**Issue by tangli159** [chongshengB/rt-n56u#158]
机型k2p.usb。才刷这个固件0319的时候能用，但是后来我把u盘格式化后再插入，尽管u盘里面还有opt 镜像，caddy 等文件夹，打开文件管理功能后运行状态都是已停止，日志未见报错，请问我需要在哪里下载一些文件把我的u盘重新设置能让固件正常开启文件管理呢？辛苦大大解答，谢谢

**Comment by xiaole51** [comment]
最近依赖云端下载执行程序的插件很多都失效了.原因是腾讯云改变了策略.
临时解决方法:
https://cdn.jsdelivr.net/gh/chongshengB/rt-n56u/trunk/user/caddy/caddy_filebrowser
手动下载执行文件上传到/tmp/caddy下,给执行权限.
开关文件管理就可以运行了.

重启需要重复上面步骤.

最近C大很忙,代码都快一个月不维护了.

**Comment by tangli159** [comment]
> 最近依赖云端下载执行程序的插件很多都失效了.原因是腾讯云改变了策略.
> 临时解决方法:
> https://cdn.jsdelivr.net/gh/chongshengB/rt-n56u/trunk/user/caddy/caddy_filebrowser
> 手动下载执行文件上传到/tmp/caddy下,给执行权限.
> 开关文件管理就可以运行了.
> 
> 重启需要重复上面步骤.
> 
> 最近C大很忙,代码都快一个月不维护了.

亲测有效，下载文件通过winscp拷贝文件进入相关文件夹（路由器上文件管理设置的是哪个文件夹就是哪个，不一定是tmp），给予权限，然后关闭再开启文件管理，开心！
