### ISSUE TITLE
内网控制：全部走代理，是指上国内网也会走代理吗？

### ISSUE THREAD

**Issue by fireontable** [chongshengB/rt-n56u#166]
如题，即便运行规则选择gfwlist，也会所有网站都通过代理连接吗？

**Comment by fireontable** [comment]
一旦选择指定ip走代理，就翻不出去了。。。。

**Comment by sensen1** [comment]
内网控制，是用于控制路由下面的机器，不都能够使用ssr服务的吧，和国内没有关系。

**Comment by mzit** [comment]
> 一旦选择指定ip走代理，就翻不出去了。。。。

规则选gfw 内网控制选指定ip走代理 那只会让规则管理里的强制走SS代理的LAN IP去走gfwlist规则

**Comment by sensen1** [comment]
> > 一旦选择指定ip走代理，就翻不出去了。。。。
> 
> 规则选gfw 内网控制选指定ip走代理 那只会让规则管理里的强制走SS代理的LAN IP去走gfwlist规则

想问一下，规则管理里，你自定义强制走代理 的 域名 或者 ip 有效吗？
我这里这个功能一直不起作用

**Comment by chongshengB** [comment]
估计是一个bug，我看看
