### ISSUE TITLE
B70没有2.4G WIFI，5GWIFI正常。

### ISSUE THREAD

**Issue by SouHong** [chongshengB/rt-n56u#17]
B70没有2.4G WIFI，5GWIFI正常。

**Comment by chongshengB** [comment]
我之前给人测试反馈的正常的，我自己没有硬件，你看看是不是内核配置问题。

**Comment by SouHong** [comment]
显示有2.4G的WIFI，是无法连接。是否与使用的驱动有关？

**Comment by SouHong** [comment]
https://www.right.com.cn/forum/thread-2048716-1-1.html

[B70.zip](https://github.com/chongshengB/rt-n56u/files/4014923/B70.zip)
