### ISSUE TITLE
ssr更新完gfw之后 依旧无法上网

### ISSUE THREAD

**Issue by yellowstrong** [chongshengB/rt-n56u#170]
在手动更新gfw之后，google，youtube便无法打开 不知道大家有没有也遇到这个问题，不更新之前是可以正常打开上网的

**Comment by icy37785** [comment]
感觉你或许需要 ipconfig /flushdns

**Comment by yellowstrong** [comment]
> 感觉你或许需要 ipconfig /flushdns

试过了 并没有用

**Comment by yellowstrong** [comment]
好像是C大编译的包的问题 我自己编译的刷过之后没问题了
