### ISSUE TITLE
最新源码云编译transmission过不去，求解决办法

### ISSUE THREAD

**Issue by fbrav530** [chongshengB/rt-n56u#171]
Makefile:1249: recipe for target 'crypto-utils-openssl.o' failed
make[4]: Leaving directory '/opt/rt-n56u/trunk/user/transmission/transmission-2.9xbtransmission'
make[4]: *** [crypto-utils-openssl.o] Error 1
Makefile:502: recipe for target 'all-recursive' failed
make[3]: Leaving directory '/opt/rt-n56u/trunk/user/transmission/transmission-2.9x'
make[3]: *** [all-recursive] Error 1
Makefile:9: recipe for target 'all' failed
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/transmission'
make[2]: *** [all] Error 2
Makefile:225: recipe for target 'all' failed
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
make[1]: *** [all] Error 2
Makefile:202: recipe for target 'user_only' failed
make: *** [user_only] Error 2

我搜到这里有个补丁，但太菜，不会用，希望老大加入
https://cndaqiang.github.io/2018/11/17/transmision_skip/

**Comment by chongshengB** [comment]
已修正，可以同步最新源码测试下
