### ISSUE TITLE
启用ss节点后，客户端仍然显示已停止

### ISSUE THREAD

**Issue by Benjamin23333** [chongshengB/rt-n56u#174]
原来用的是hiboy的老毛子，看到您的移植了ssr+，就试了下这个，发现ss节点选为主服务器并开启后，仍然显示“已停止”，ssr节点和v2ray节点没有这种现象，我记得这个是ssr+几天之前的bug了，已经修复了，可以麻烦您同步一下吗？

**Comment by chongshengB** [comment]
我看看吧

**Comment by FunCatcher** [comment]
一样的问题，ss无法启动，但ssr可以
