### ISSUE TITLE
Dir878更新4.17的版本失败

### ISSUE THREAD

**Issue by BlackJackonGH** [chongshengB/rt-n56u#179]
友讯DIR878从breed更新固件DIR-878_3.4.3.9-099.trx，完成后网络连接断开，路由器上只有电源灯亮，重启多次都一样。

**Comment by BlackJackonGH** [comment]
自己手动编译了一个文件，更新后正常。

**Comment by zhaoyushi** [comment]
> 自己手动编译了一个文件，更新后正常。

您好，具体是怎么弄的呀…我也是878

**Comment by BlackJackonGH** [comment]
> > 自己手动编译了一个文件，更新后正常。
> 
> 您好，具体是怎么弄的呀…我也是878
用的作者的自动编译项目
https://github.com/chongshengB/Padavan-build

**Comment by zhaoyushi** [comment]
朋友，您有419版本编译好的878固件吗？0507的SSP+不太好用，想求一个easthutong@gmail.com
