### ISSUE TITLE
 找不到 /opt/bin/chinadns_ng,然后ss/frp之类的都掉了

### ISSUE THREAD

**Issue by lee29** [chongshengB/rt-n56u#185]
【chinadns_ng】: 找不到 /opt/bin/chinadns_ng，安装 opt 程序
Apr 19 17:45:03 【opt】: opt 挂载正常：tmpfs
Apr 19 17:45:03 【file】: 找不到 /opt/bin/chinadns_ng ，重新下载数据，请稍后
Apr 19 17:45:03 【file】: 下载完成 /opt/bin/chinadns_ng
Apr 19 17:45:03 【file】: 找不到 /opt/bin/chinadns_ng ，重新下载数据，请稍后
Apr 19 17:45:03 【file】: 下载完成 /opt/bin/chinadns_ng
Apr 19 17:45:03 【chinadns_ng】: 找不到 /opt/bin/chinadns_ng ，需要手动安装 /opt/bin/chinadns_ng
Apr 19 17:45:03 【chinadns_ng】: 启动失败, 10 秒后自动尝试重新启动

**Comment by chongshengB** [comment]
这不是我的固件，你找这个固件作者反馈吧

**Comment by lee29** [comment]
> 这不是我的固件，你找这个固件作者反馈吧

这个模板可以在build的时候编译进去么，没找到具体的模块名称
