### ISSUE TITLE
请楼主适配LINKSYS RE6500

### ISSUE THREAD

**Issue by ihuaer** [chongshengB/rt-n56u#186]
RE6500可以刷WR1200JS_3.4.3.9-099.trx，但是没有无线。其他正常，请楼主看看有没有机会适配无线？

Model | Version
RE6500

SoC
MediaTek MT7621AT

Flash MB
8MB

RAM MB
64

WLAN Hardware
MediaTek MT7602EN, MediaTek MT7612EN

**Comment by chongshengB** [comment]
[RE6500_3.4.3.9-099.zip](https://github.com/chongshengB/rt-n56u/files/4501274/RE6500_3.4.3.9-099.zip)

你测试下，我没条件测试

**Comment by ihuaer** [comment]
> [RE6500_3.4.3.9-099.zip](https://github.com/chongshengB/rt-n56u/files/4501274/RE6500_3.4.3.9-099.zip)
> 
> 你测试下，我没条件测试

你好，群主，这款固件无线可以用。谢谢
后续有机会请添加更新。

**Comment by chongshengB** [comment]
> > [RE6500_3.4.3.9-099.zip](https://github.com/chongshengB/rt-n56u/files/4501274/RE6500_3.4.3.9-099.zip)
> > 你测试下，我没条件测试
> 
> 你好，群主，这款固件无线可以用。谢谢
> 后续有机会请添加更新。

其它的正常么？led灯和网口，

**Comment by ihuaer** [comment]
> > > [RE6500_3.4.3.9-099.zip](https://github.com/chongshengB/rt-n56u/files/4501274/RE6500_3.4.3.9-099.zip)
> > > 你测试下，我没条件测试
> > 
> > 
> > 你好，群主，这款固件无线可以用。谢谢
> > 后续有机会请添加更新。
> 
> 其它的正常么？led灯和网口，

网口和LED灯正常

**Comment by chongshengB** [comment]
已推送到源码，后期有问题再修改 吧
