### ISSUE TITLE
日志ssr-redir[584]: remote recv: Connection reset by peer

### ISSUE THREAD

**Issue by phenixess** [chongshengB/rt-n56u#189]
Apr 21 19:39:07 ssr-redir[584]: remote recv: Connection reset by peer
Apr 21 19:39:23 ssr-redir[587]: remote recv: Connection reset by peer
Apr 21 19:39:58 ssr-redir[587]: remote recv: Connection reset by peer
Apr 21 19:40:21 ssr-redir[587]: remote recv: Connection reset by peer
Apr 21 19:40:43 ssr-redir[587]: server recv: Connection reset by peer
Apr 21 19:40:57 ssr-redir[584]: remote recv: Connection reset by peer
Apr 21 19:41:02 ssr-redir[584]: remote recv: Connection reset by peer
Apr 21 19:41:06 ssr-redir[584]: remote recv: Connection reset by peer
Apr 21 19:41:08 ssr-redir[587]: remote recv: Connection reset by peer
Apr 21 19:41:08 ssr-redir[590]: remote recv: Connection reset by peer
Apr 21 19:41:09 ssr-redir[584]: remote recv: Connection reset by peer
Apr 21 19:41:09 ssr-redir[590]: remote recv: Connection reset by peer
Apr 21 19:41:17 ssr-redir[584]: remote recv: Connection reset by peer
Apr 21 19:41:18 ssr-redir[572]: remote recv: Connection reset by peer
Apr 21 19:41:27 ssr-redir[587]: remote recv: Connection reset by peer
这个啥问题

**Comment by icy37785** [comment]
这个提示不理他就可以了。。。。其实我也希望可以屏蔽掉这些。。。
