### ISSUE TITLE
jq程序未默认安装导致v2ray失败

### ISSUE THREAD

**Issue by xumng** [chongshengB/rt-n56u#190]
log如下：
> Apr 21 06:58:36 admin: 运行后 WAN 状态: WAN 状态:【up】, WAN 接口:【ppp0】, WAN IP:【100.64.56.255】
Apr 21 06:58:36 【v2ray】: 找不到 jq，需要手动安装 opt 后输入[opkg update; opkg install jq]安装
Apr 21 06:58:36 【v2ray】: 错误！找不到 jq 程序
Apr 21 06:58:36 【WebUI】: UI 开关遍历状态监测
Apr 21 06:58:36 【opt】: opt 挂载正常：tmpfs
Apr 21 06:58:36 【opt】: 自动安装（覆盖 opt 文件夹）
Apr 21 06:58:36 【opt】: opt 第一次下载/opt/opt.tgz
Apr 21 06:58:36 【opt】: /opt 可用空间：125M
Apr 21 06:58:36 【opt】: 下载: https://opt.cn2qq.com/opt-file/opttmpg8.tgz
Apr 21 06:58:36 【opt】: /opt/opt.tgz 下载完成，开始解压
Apr 21 06:58:36 【opt】: /opt/opt.tgz 下载失败
Apr 21 06:58:36 【opt】: opt 第二次下载/opt/opt.tgz
Apr 21 06:58:36 【opt】: /opt 可用空间：125M
Apr 21 06:58:36 【opt】: 下载: https://opt.cn2qq.com/opt-file/opttmpg8.tgz
Apr 21 06:58:36 【opt】: opt 挂载正常：tmpfs

查看代码，在shadowsocks目录下存在jq，默认能否编译进去？

**Comment by icy37785** [comment]
你用的HIboy的固件在这里发issues有啥用呀，这边的固件早就不用jq了。。。

**Comment by xumng** [comment]
看了代码，的确有jq的调用。
