### ISSUE TITLE
启动SS失败，提示找不到tmpfs

### ISSUE THREAD

**Issue by xumng** [chongshengB/rt-n56u#192]
> Apr 21 21:34:18 【SS】: 启动 SS
Apr 21 21:34:18 【SS】: ss-redir start.【】
Apr 21 21:34:18 【SS】: ###############启动程序###############
Apr 21 21:34:18 【ss-redir】: 启动所有的 ss-redir 连线, 出现的 SS 日志并不是错误报告, 只是使用状态日志, 请不要慌张, 只要系统正常你又看不懂就无视它！
Apr 21 21:34:18 【ss-redir】: SS服务器【】设置内容：127.0.0.1 端口:8989 加密方式:none 本地监听地址：0.0.0.0 本地代理端口：1090 
Apr 21 21:34:18 【SS】: 找不到 ss-redir 、 ss-local 、  或 obfs-local ，挂载opt
Apr 21 21:34:19 【opt】: opt 挂载正常：tmpfs
Apr 21 21:34:19 【SS_1_redir】:   2020-04-21 21:34:19 INFO: initializing ciphers... none
Apr 21 21:34:19 【SS_1_redir】:   2020-04-21 21:34:19 ERROR: invalid cipher name: none
Apr 21 21:34:19 【SS_1_redir】:   2020-04-21 21:34:19 ERROR: failed to initialize ciphers
Apr 21 21:34:20 【SS】: 启动失败, 注意检查端口是否有冲突,程序是否下载完整,10 秒后自动尝试重新启动
Apr 21 21:34:30 【ss】: 多次尝试启动失败，等待【19分钟】后自动尝试重新启动

**Comment by icy37785** [comment]
你用的HIboy的固件在这里发issues有啥用呀，这边的固件病没有这问题。

**Comment by xumng** [comment]
没有双清，所以每次都有如上问题
