### ISSUE TITLE
SSR好像不能使用，

### ISSUE THREAD

**Issue by wwz09** [chongshengB/rt-n56u#2]
Dec 15 09:23:08 SS: 正在启动SS程序...
Dec 15 09:23:08 SS: 正在创建json文件...
Dec 15 09:23:08 ssr-redir[5676]: initializing ciphers... none
Dec 15 09:23:08 ssr-redir[5678]: initializing ciphers... none
Dec 15 09:23:08 ssr-redir[5680]: initializing ciphers... none
Dec 15 09:23:08 ssr-redir[5682]: initializing ciphers... none
Dec 15 09:23:08 SS: 正在启动pdnsd...
Dec 15 09:23:08 pdnsd[5692]: pdnsd-1.2.9b-par starting.
Dec 15 09:23:08 SS: 正在添加防火墙规则...
Dec 15 09:23:10 ssr-redir[5678]: listening at 0.0.0.0:1080
Dec 15 09:23:10 ssr-redir[5678]: running from root user
Dec 15 09:23:10 ssr-redir[5680]: bind: Address already in use
Dec 15 09:23:10 ssr-redir[5680]: Could not bind
Dec 15 09:23:10 ssr-redir[5680]: bind() error
Dec 15 09:23:10 ssr-redir[5682]: bind: Address already in use
Dec 15 09:23:10 ssr-redir[5682]: Could not bind
Dec 15 09:23:10 ssr-redir[5682]: bind() error
Dec 15 09:23:11 ssr-redir[5676]: bind: Address already in use
Dec 15 09:23:11 ssr-redir[5676]: Could not bind
Dec 15 09:23:11 ssr-redir[5676]: bind() error
Dec 15 09:23:13 dnsmasq[5647]: exiting on receipt of SIGTERM
Dec 15 09:23:13 dnsmasq[5737]: started, version 2.78 cachesize 1536
Dec 15 09:23:13 dnsmasq[5737]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Dec 15 09:23:13 dnsmasq-dhcp[5737]: DHCP, IP range 192.168.2.100 -- 192.168.2.244, lease time 1d
Dec 15 09:23:13 dnsmasq-dhcp[5737]: DHCP, sockets bound exclusively to interface br0
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zzux.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zzcloud.me 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zzcartoon.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zyzc9.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zyns.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zynamics.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zynaima.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zvereff.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zuola.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zuo.la 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zuobiao.me 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zsrhao.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zspeeder.me 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zpn.im 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zozotown.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zorrovpn.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zoozle.net 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zootool.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zoogvpn.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.net 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zonaeuropa.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zomobo.net 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zodgame.us 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zmw.cn 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zkaip.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zippyshare.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain ziporn.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zinio.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zim.vn 
Dec 15 09:23:13 SS: 启动成功。
Dec 15 09:23:13 dnsmasq[5737]: using 11373 more nameservers
Dec 15 09:23:13 dnsmasq[5737]: read /etc/hosts - 3 addresses
Dec 15 09:23:13 dnsmasq[5737]: read /etc/storage/dnsmasq/hosts - 0 addresses
Dec 15 09:23:13 dnsmasq-dhcp[5737]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zzux.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zzcloud.me 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zzcartoon.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zyzc9.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zyns.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zynamics.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zynaima.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zvereff.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zuola.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zuo.la 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zuobiao.me 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zsrhao.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zspeeder.me 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zpn.im 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zozotown.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zorrovpn.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zoozle.net 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zootool.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zoogvpn.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.net 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zonaeuropa.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zomobo.net 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zodgame.us 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zmw.cn 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zkaip.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zippyshare.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain ziporn.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zinio.com 
Dec 15 09:23:13 dnsmasq[5737]: using nameserver 127.0.0.1#5353 for domain zim.vn 
Dec 15 09:23:13 dnsmasq[5737]: using 11374 more nameservers
Dec 15 09:23:43 shadowsocksr: ��⵽SS���̹ҵ�����������!
Dec 15 09:23:43 dnsmasq[5737]: exiting on receipt of SIGTERM
Dec 15 09:23:43 dnsmasq[5825]: started, version 2.78 cachesize 1536
Dec 15 09:23:43 dnsmasq[5825]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Dec 15 09:23:43 dnsmasq-dhcp[5825]: DHCP, IP range 192.168.2.100 -- 192.168.2.244, lease time 1d
Dec 15 09:23:43 dnsmasq-dhcp[5825]: DHCP, sockets bound exclusively to interface br0
Dec 15 09:23:43 dnsmasq[5825]: read /etc/hosts - 3 addresses
Dec 15 09:23:43 dnsmasq[5825]: read /etc/storage/dnsmasq/hosts - 0 addresses
Dec 15 09:23:43 dnsmasq-dhcp[5825]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Dec 15 09:23:43 dnsmasq[5825]: using nameserver 192.168.100.1#53
Dec 15 09:23:43 SS: 正在启动SS程序...
Dec 15 09:23:43 SS: 正在创建json文件...
Dec 15 09:23:43 ssr-redir[5854]: initializing ciphers... none
Dec 15 09:23:43 ssr-redir[5856]: initializing ciphers... none
Dec 15 09:23:43 ssr-redir[5858]: initializing ciphers... none
Dec 15 09:23:43 ssr-redir[5860]: initializing ciphers... none
Dec 15 09:23:44 SS: 正在启动pdnsd...
Dec 15 09:23:44 pdnsd[5870]: pdnsd-1.2.9b-par starting.
Dec 15 09:23:44 SS: 正在添加防火墙规则...
Dec 15 09:23:46 ssr-redir[5854]: listening at 0.0.0.0:1080
Dec 15 09:23:46 ssr-redir[5854]: running from root user
Dec 15 09:23:46 ssr-redir[5858]: bind: Address already in use
Dec 15 09:23:46 ssr-redir[5858]: Could not bind
Dec 15 09:23:46 ssr-redir[5858]: bind() error
Dec 15 09:23:46 ssr-redir[5856]: bind: Address already in use
Dec 15 09:23:46 ssr-redir[5856]: Could not bind
Dec 15 09:23:46 ssr-redir[5856]: bind() error
Dec 15 09:23:46 ssr-redir[5860]: bind: Address already in use
Dec 15 09:23:46 ssr-redir[5860]: Could not bind
Dec 15 09:23:46 ssr-redir[5860]: bind() error
Dec 15 09:23:48 dnsmasq[5825]: exiting on receipt of SIGTERM
Dec 15 09:23:48 dnsmasq[5915]: started, version 2.78 cachesize 1536
Dec 15 09:23:48 dnsmasq[5915]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Dec 15 09:23:48 dnsmasq-dhcp[5915]: DHCP, IP range 192.168.2.100 -- 192.168.2.244, lease time 1d
Dec 15 09:23:48 dnsmasq-dhcp[5915]: DHCP, sockets bound exclusively to interface br0
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zzux.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zzcloud.me 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zzcartoon.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zyzc9.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zyns.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zynamics.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zynaima.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zvereff.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zuola.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zuo.la 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zuobiao.me 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zsrhao.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zspeeder.me 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zpn.im 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zozotown.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zorrovpn.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zoozle.net 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zootool.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zoogvpn.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.net 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zonaeuropa.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zomobo.net 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zodgame.us 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zmw.cn 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zkaip.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zippyshare.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain ziporn.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zinio.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zim.vn 
Dec 15 09:23:48 SS: 启动成功。
Dec 15 09:23:48 dnsmasq[5915]: using 11373 more nameservers
Dec 15 09:23:48 dnsmasq[5915]: read /etc/hosts - 3 addresses
Dec 15 09:23:48 dnsmasq[5915]: read /etc/storage/dnsmasq/hosts - 0 addresses
Dec 15 09:23:48 dnsmasq-dhcp[5915]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zzux.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zzcloud.me 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zzcartoon.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zyzc9.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zyns.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zynamics.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zynaima.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zvereff.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zuola.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zuo.la 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zuobiao.me 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zsrhao.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zspeeder.me 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zpn.im 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zozotown.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zorrovpn.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zoozle.net 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zootool.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zoogvpn.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.net 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zonghexinwen.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zonaeuropa.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zomobo.net 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zodgame.us 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zmw.cn 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zkaip.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zippyshare.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain ziporn.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zinio.com 
Dec 15 09:23:48 dnsmasq[5915]: using nameserver 127.0.0.1#5353 for domain zim.vn 
Dec 15 09:23:48 dnsmasq[5915]: using 11374 more nameservers

**Comment by sw1999** [comment]
确实用不了，求修复，newifi3默认4个进程，端口也是提示错误。
Dec 15 09:23:46 ssr-redir[5854]: listening at 0.0.0.0:1080
Dec 15 09:23:46 ssr-redir[5854]: running from root user
Dec 15 09:23:46 ssr-redir[5858]: bind: Address already in use
Dec 15 09:23:46 ssr-redir[5858]: Could not bind
Dec 15 09:23:46 ssr-redir[5858]: bind() error
