### ISSUE TITLE
报告事项,仅仅新路由三固件(NEWIFI3)bug

### ISSUE THREAD

**Issue by mida2011** [chongshengB/rt-n56u#213]
报告事项,仅仅新路由三固件(NEWIFI3)bug，k2p测试正常无此bug：
4月30日最源码编译的新路由三(NEWIFI3)固件：
2.4G无线桥接，“AP-client+AP”这个桥接模式无法连接；

同时编译的k2p无此bug。

**Comment by mida2011** [comment]
仅仅新路由三固件(NEWIFI3)bug，2.4G无线桥接，“AP-client+AP”这个桥接模式无法连接；
因为您的固件 优秀，希望完善这个小问题，谢谢

**Comment by xiaole51** [comment]
这功能没问题,一直用2.4G桥接使用.
初始化一下设置试试.

**Comment by mida2011** [comment]
> 这功能没问题,一直用2.4G桥接使用.
> 初始化一下设置试试.

谢谢回复。
我下午就三清后，再试试新路由3的这个2.4G桥接+ap。然后反馈。
 此致
 礼

**Comment by mida2011** [comment]
> 这功能没问题,一直用2.4G桥接使用.
> 初始化一下设置试试.

重置、三清后，新路由三固件(NEWIFI3)，2.4G无线桥接，“AP-client+AP”这个桥接模式依然无法连接；

网络信息-->无线 2.4G 信息如下:

Operation Mode	: AP-Client + AP
WPHY Mode	: 11g/n
Channel Main	: 2
STA Connected	: NO

**Comment by mida2011** [comment]
我有10台新路由三，新机器测试也是如此。应该是个小bug，烦请修正。
现在除了footlog的固件没这个bug，所有基于chongshengB制作的新路由三固件，都有这个小问题。
此致
礼

**Comment by mida2011** [comment]
> 这功能没问题,一直用2.4G桥接使用.
> 初始化一下设置试试.

根据建议，双重置、breed清理后，新路由三固件bug依旧，还请修复，谢谢！
此致
礼
