### ISSUE TITLE
能否考虑更新k2p无线驱动

### ISSUE THREAD

**Issue by keanu131** [chongshengB/rt-n56u#217]
如题，参见https://www.right.com.cn/forum/thread-3979275-1-1.html
本人测试，不仅2.4G信号有提升，主要是5G响应速度好了很多。

**Comment by ruabbit233** [comment]
那楼主用的不就是这个编译的吗？

**Comment by liyufan** [comment]
https://github.com/chongshengB/rt-n56u/commit/80c6938efa647a5f6adfe03c17138b2dc7cc47de

**Comment by ghost** [comment]
晕 那个人就是用hanwckf和chongshengB的源码来制作的  估计就是用c大github云编译来弄的   
一点自己的东西都没有  介绍的还以为很厉害

**Comment by ghost** [comment]
https://www.right.com.cn/forum/thread-1673645-1-1.html
这是教程  你自己也可以云编译你想要的固件

**Comment by keanu131** [comment]
> [80c6938](https://github.com/chongshengB/rt-n56u/commit/80c6938efa647a5f6adfe03c17138b2dc7cc47de)

> https://www.right.com.cn/forum/thread-1673645-1-1.html
> 这是教程 你自己也可以云编译你想要的固件

明白，我是对0419固件提的建议。毕竟还有很多人跟我一样，只是使用C大编译好的固件

**Comment by MeIsReallyBa** [comment]
> anwckf和chongshengB的源码来制作的 估计就是用c大github云编译来弄的
> 一点自己的东西都没有 介绍的还以为很厉害

莫名其妙受到diss。你去问问chongshengB 5.0.4.0是谁发给他的？

**Comment by ningsibuqu** [comment]
> > anwckf和chongshengB的源码来制作的 估计就是用c大github云编译来弄的
> > 一点自己的东西都没有 介绍的还以为很厉害
> 
> 莫名其妙受到diss。你去问问chongshengB 5.0.4.0是谁发给他的？

大佬，你那边能编译一版 nano 版吗？
我看这边和你那边都没有 nano 版，hanwckf 那边又不更新 5.0.4.0…
