### ISSUE TITLE
为啥选中很多原版的软件了，编译后还是只有科学上网和smartdns等新软件啊

### ISSUE THREAD

**Issue by martin0607** [chongshengB/rt-n56u#23]
为啥选中很多原版的软件了，编译后还是只有科学上网和smartdns等新软件啊

**Comment by chongshengB** [comment]
什么型号？选了那些软件？方便把config文件发上来看看？不然我真的无法解答

**Comment by martin0607** [comment]
> 什么型号？选了那些软件？方便把config文件发上来看看？不然我真的无法解答


[build-padavan.yml.txt](https://github.com/chongshengB/rt-n56u/files/4019527/build-padavan.yml.txt)
谢谢大佬看一下吧
