### ISSUE TITLE
反馈问题 小米AC2100(R2100)刷5.7最新固件后界面为英文

### ISSUE THREAD

**Issue by 7-Guys** [chongshengB/rt-n56u#252]
进入系统设置后只有英文和俄文两种语言

**Comment by butinhi** [comment]
You can change language in R2100.config

**Comment by liyufan** [comment]
https://github.com/chongshengB/rt-n56u/blob/618fb2de82fcd65157d2b1a7fb1a8ffbcdefc700/trunk/configs/templates/R2100.config#L112
请自行修改

**Comment by chongshengB** [comment]
fixed
