### ISSUE TITLE
（已解决！如有更好方法请指点）请教下frpc如何使用？

### ISSUE THREAD

**Issue by fbrav530** [chongshengB/rt-n56u#26]
请教下frpc如何使用？编译进去了，/usr/bin里面也有frpc文件，没有菜单，不知道怎样调用？

**Comment by fbrav530** [comment]
已解决，把h大固件里面的脚本稍改下，粘到 参数设置- 在 WAN 上行/下行启动后执行:里面

killall frpc
mkdir -p /tmp/frp
cat > "/tmp/frp/myfrpc.ini" <<-\EOF
[common]
server_addr = frp服务器IP或域名
server_port = 端口
token = 你的token

#log_file = /dev/null
#log_level = info
#log_max_days = 3

[padvan]
remote_port = 8088
type = tcp
local_ip = 192.168.2.1
local_port = 80
subdomain = padvan
#host_header_rewrite = 实际你内网访问的域名，可以供公网的域名不一致，如果一致可以不写
EOF
frpc -c /tmp/frp/myfrpc.ini 2>&1 &

**Comment by chongshengB** [comment]
已集成web界面
