### ISSUE TITLE
使用v2ray 在 断电通电后 wifi不能正常连接 获取不到ip

### ISSUE THREAD

**Issue by ju869** [chongshengB/rt-n56u#269]
K2P 使用v2ray 在 断电通电后 wifi不能正常连接 获取不到ip 网线直连电脑也是获取不到ip 需恢复默认设置 使用ssr断电通电后连接却正常

**Comment by yang12me** [comment]
看下系统日志，内网LAN - DHCP服务器 - 自定义配置文件 "dnsmasq.conf"，注释掉相关行
