### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ntgeralt** [chongshengB/rt-n56u#28]
你好，发现你plus插件做得很好，在padavan开了ui先例。
有几点建议，
一个是BT下载似乎走v2ray海外流量（国外模式）
![image](https://user-images.githubusercontent.com/8230651/71947431-cfc25200-3207-11ea-878c-62e7414eb799.png)

还有些plus界面，一些个人建议：

![image](https://user-images.githubusercontent.com/8230651/71947512-1152fd00-3208-11ea-853a-d49c7a2f59ea.png)

![image](https://user-images.githubusercontent.com/8230651/71947532-22037300-3208-11ea-89ba-79bd72e50a0c.png)

[添加节点URL]，那里可以改为可以做成一个文本框，后面一个添加按钮
导入v2rayN.exe的vmess ws tls 链接时，tls默认没勾选。不过那也是vmess 各家不同的老问题了。
一些个人建议，你看下就好

**Comment by chongshengB** [comment]
感谢您的建议，我看看可以怎么调整一下不合理的地方。
BT下载这个我要测试下

**Comment by ntgeralt** [comment]
另外plus+主页的运行状态，打开开关能上google后，如果不F5，仍然显示[已停止]. 稍微有点错觉

**Comment by chongshengB** [comment]
它的状态获取是通过页面载入执行对应的js代码，然后获取当前进程是否运行，当页面载入，程序还未运行完成，状态还是停止，需要刷新才会获取新状态，这个问题兄弟有无更好的替代方法？

**Comment by ntgeralt** [comment]
您好，看能否做个自动F5刷新，或者不显示那个，像lean那样启动后显示已启动。

**Comment by ntgeralt** [comment]
![image](https://user-images.githubusercontent.com/8230651/72082721-8ffc8700-333b-11ea-98bf-2e4757a6f33a.png)

v2ray国外模式访问www.google.com.hk有问题

**Comment by ntgeralt** [comment]
我看错了，访问www.google.com.hk正常..

**Comment by ntgeralt** [comment]
你看看有没有这问题：v2 gfwlist模式时访问大陆公网非标端口网盘无法打开，关掉v2又能打开
