### ISSUE TITLE
大家ShadowSocksR Plus+是怎么配置的？gfw模式无效

### ISSUE THREAD

**Issue by lihuixian001** [chongshengB/rt-n56u#292]
0507版本，测试验证gfw模式无法使用，规则配置里面设置强制走ss的域名也无效
现在只能使用“绕过大陆模式”，但是这个模式会将没必要走代理的也走代理了

现在希望类似ShadowSocks pac模式这样的效果，有办法做到吗？

**Comment by zouyonghao** [comment]
0419可以正常使用，尝试切换一下DNS？

**Comment by sensen1** [comment]
> 0419可以正常使用，尝试切换一下DNS？

我也是定在0419版本，没有再更新。

**Comment by lihuixian001** [comment]
0507版本  小米ac2100  怎么切dns都没有用， 连强制域名走ss也没用

**Comment by ntgeralt** [comment]
gfwlist会有个反应时间。客户端重新插拔网线解决

**Comment by zouyonghao** [comment]
~我升级了版本之后使用`gfwlist`模式也不行了~
切到了`绕过大陆模式`，DNS换成`8.8.8.8`，切回`gfwlist`之后又可以了，建议切换模式，清空dns，试下`8.8.8.8`能否访问

**Comment by lihuixian001** [comment]
@zouyonghao 谢谢提示！电脑dns设置为路由器ip就可以了
