### ISSUE TITLE
新3和K2P-USB都有软重启无法开机的BUG

### ISSUE THREAD

**Issue by kiddy99** [chongshengB/rt-n56u#3]
具体表现为，点击路由器管理页面重启按钮。
K2P-USB，有1/5的概率，亮红灯，无法启动。
新三，有1/5的概率，不亮灯，无法启动。
以上需要手动拔掉电源，重新插入才能开机。
应该是hanwckf最新源码的问题，用他的源码编译同样出了类似问题。
hiboy也同步了Hanwckf源码，也出现了同样的问题。
希望大神能够修补这一BUG，万分感谢！ORZ

**Comment by ZeroIP** [comment]
我之前有向hanwckf反映过类似的问题。他回复说可能是新3的32m flash导致的老问题，可以尝试将breed换成pd-boot。你可以试试看。

**Comment by Liushuixian423** [comment]
现在自动编译的固件怎么没有了K2P-USB固件了啊？

**Comment by chongshengB** [comment]
已修复，明天更新固件

**Comment by ntgeralt** [comment]
你好，我试用你##2020.01.03##的新路由3固件，发现你似乎修复好了重启概率死机的问题，我新3重启了四五次也正常
