### ISSUE TITLE
RM2100网络信息下WAN和LAN不显示内容

### ISSUE THREAD

**Issue by aliensvx** [chongshengB/rt-n56u#307]
![image](https://user-images.githubusercontent.com/7090204/84096112-9cdcee00-aa33-11ea-8d6d-793049a11681.png)
WAN和LAN都显示<% dump_eth_mib(); %>
固件版本3.4.3.9-099_20200604

**Comment by butinhi** [comment]
Me too.

**Comment by YJWangGH** [comment]
NEWIFI-MINI 同样问题
