### ISSUE TITLE
NEWIFI-MINI 科学上网 - ShadowSocksR Plus+ SOCKS5代理 不能启动

### ISSUE THREAD

**Issue by YJWangGH** [chongshengB/rt-n56u#316]
运行日志：Global_Socks5:Can't find  program, can't start!

**Comment by Dedogordo** [comment]
我的360P2也是这个情况，感觉前几天更新了shadowsocks插件后编译出来的都启动不了，之前编译还是ok的，因为我发现shadowsocks的添加节点页面变了所以应该是更新了，我的固件编译好后提示找不到trojan，同样也有个sock5问题，求大佬指点，报错如下（我编译的时候仅仅改了firmware build modify 里把shaodowsocket的开关打开n改y，其他都没动）：

Main node:Can't find /usr/bin/trojan program, can't start!
Global_Socks5:Can't find  program, can't start!

**Comment by q4w5e6** [comment]
你没有把socks5编译进去吧。

**Comment by YJWangGH** [comment]
> 你没有把socks5编译进去吧。

谢谢！自动编译没有socks5，添加socks5后编译正常启动

**Comment by YJWangGH** [comment]
#299
