### ISSUE TITLE
NEWIFI3的Release里自动编译的0604版科学上网“游戏 UDP 中继服务器”问题

### ISSUE THREAD

**Issue by esverde** [chongshengB/rt-n56u#327]
运行日志显示“UDP TPROXY Relay:Can't find  program, can't start!”，自编译的0619也有这问题

**Comment by YJWangGH** [comment]
NEWIFI-MINI 试了下也有相同的问题，应该是相关插件没有编译进去

**Comment by YJWangGH** [comment]
解决问题了吗？是哪里的问题请明示
