### ISSUE TITLE
NEWIFI-MINI 科学上网 游戏UDP中继服务器 不能启动

### ISSUE THREAD

**Issue by YJWangGH** [chongshengB/rt-n56u#328]
运行日志：UDP TPROXY Relay:Can't find  program, can't start!

自己编译的和20200619编译的Releases都一样，不知道是缺少那个插件。

**Comment by esverde** [comment]
先选一个服务器应用，然后再改回与主服务器相同即可，可见https://github.com/chongshengB/rt-n56u/issues/299#issuecomment-643212007
