### ISSUE TITLE
curl的编译的make参数可以优化下，否则编译出来的curl无法使用https

### ISSUE THREAD

**Issue by bluehj777** [chongshengB/rt-n56u#330]
目前编译出来的curl不支持https
=======================
执行
curl https://www.baidu.com
curl: (60) Cert verify failed: BADCERT_NOT_TRUSTED
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
=========================
修改下/opt/rt-n56u/trunk/libs/libcurl/Makefile的configure参数 对应改为
--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt \
--with-ssl \
编译后curl 支持https没有问题
curl -v https://www.baidu.com
> GET / HTTP/1.1
> Host: www.baidu.com
> User-Agent: curl/7.65.3
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
< Connection: keep-alive
< Content-Length: 2443
< Content-Type: text/html
< Date: Tue, 23 Jun 2020 05:47:21 GMT
< Etag: "588603eb-98b"
< Last-Modified: Mon, 23 Jan 2017 13:23:55 GMT
< Pragma: no-cache
< Server: bfe/1.0.8.18
< Set-Cookie: BDORZ=27315; max-age=86400; domain=.baidu.com; path=/
<
<!DOCTYPE html>
........

**Comment by ag2s20150909** [comment]
使用curl -k 不就行了
