### ISSUE TITLE
酸酸乳全局模式无效

### ISSUE THREAD

**Issue by wangziyingwen** [chongshengB/rt-n56u#34]
![Screenshot_20200112-093632](https://user-images.githubusercontent.com/21355001/72212850-803d9800-351f-11ea-8234-32178ece70f8.png)
日志一直显示打开太多文件，然后空闲疯狂往下掉。

**Comment by fr0zenrain** [comment]
maybe fd leak

**Comment by SouHong** [comment]
内网控制  选择指定IP走代理  再到规则管理页面“强制走SS代理的LAN IP”添加需要走代理的IP。
