### ISSUE TITLE
Action编译的脚本不能够将/tmp中的程序自动拷贝到/usr/bin

### ISSUE THREAD

**Issue by leegyack** [chongshengB/rt-n56u#346]
用padavan-build编译了个619版固件，科学客户端显示已连接，但是运行日志表示“Can't found v**y program under /usr/bin ,the program start failed"(大意如此）。查了一下v**y 确实未拷贝到/usr/bin下面，但是已经下载到/tmp文件夹中。由于/usr/bin 是只读的，拷贝失败。退回到419版chongshengB Release固件，就一切正常，但是在/usr/bin中也没有v**y。是不是脚本里面有差异？v**y太大，不好集成到固件里面，请教应该如何解决。

**Comment by xumng** [comment]
只能关掉不用的，将vray加上，编译进固件里。看了一下代码，不支持从tmp目录启动vray。

**Comment by chongshengB** [comment]
网上下载链接已取消，目前只能集成进固件

**Comment by leegyack** [comment]
请问，能够用ipkg install安装已经下载到/tmp的程序吗?

chongshengB <notifications@github.com> 于 2020年7月20日周一 17:09写道：
