### ISSUE TITLE
不更新了吗？最新是5月7的吗？

### ISSUE THREAD

**Issue by hrewrite** [chongshengB/rt-n56u#349]

**Comment by dxyzx0** [comment]
最新的不是6月19日么？https://github.com/chongshengB/rt-n56u/commit/7b74cdfe4a10ea34298af4ee196eaae4c90ab029

**Comment by hrewrite** [comment]
噢噢，忘了是自己编译的

**Comment by chongshengB** [comment]
最近都没更新

**Comment by Urey308** [comment]
求编译教程

**Comment by Urey308** [comment]
> 最近都没更新

大佬 我们这种不会编译的咋办Orz

**Comment by hrewrite** [comment]
凉拌，因为我也不会，周末再去找找教程去

**Comment by Urey308** [comment]
> 最近都没更新

大佬 刚刚试了下6月19那版本科学 上网 订阅地址之后好像节点还是不显示啊，怎么办

**Comment by FlyingStarlight** [comment]
> 凉拌，因为我也不会，周末再去找找教程去

fork这个https://github.com/chongshengB/Padavan-build
到自己的repositories里面，修改配置文件，然后按Star就可以自己编，在Padavan-build里面也写得非常清楚了

**Comment by FlyingStarlight** [comment]
> > 最近都没更新
> 
> 大佬 刚刚试了下6月19那版本科学 上网 订阅地址之后好像节点还是不显示啊，怎么办

请不要在别人的issue里面提自己的issue
如果你有别的疑问请单开issue
