### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by BunnyYang05** [chongshengB/rt-n56u#363]
使用昨天的源码编译v2ray时提示
**/bin/sh: 5: go: Permission denied**

详细日志如下
> make[2]: Entering directory '/opt/rt-n56u/trunk/user/v2ray'
( if [ ! -f /opt/rt-n56u/trunk/user/v2ray/v2ray-core-4.26.0.tar.gz ]; then \
curl --create-dirs -L https://codeload.github.com/v2ray/v2ray-core/tar.gz/v4.26.0 -o /opt/rt-n56u/trunk/user/v2ray/v2ray-core-4.26.0.tar.gz ; \
fi )
mkdir -p /opt/rt-n56u/trunk/user/v2ray/v2ray.com
mkdir -p /opt/rt-n56u/trunk/user/v2ray/bin
( if [ ! -d /opt/rt-n56u/trunk/user/v2ray/v2ray.com/core ]; then \
tar zxfv /opt/rt-n56u/trunk/user/v2ray/v2ray-core-4.26.0.tar.gz -C /opt/rt-n56u/trunk/user/v2ray/v2ray.com ; \
mv /opt/rt-n56u/trunk/user/v2ray/v2ray.com/v2ray-core-4.26.0 /opt/rt-n56u/trunk/user/v2ray/v2ray.com/core ; \
fi )
( cd /opt/rt-n56u/trunk/user/v2ray/"v2ray.com/core/main"; \
sed -i \
                ' s/_ "v2ray.com\/core\/main\/json"/\/\/ &/; /\/\/ _ "v2ray.com\/core\/main\/jsonem"/s/\/\/ //; s/_ "v2ray.com\/core\/main\/json"/\/\/ &/;' \
                distro/all/all.go ; \
GOOS=linux GOARCH=mipsle go build -ldflags "-w -s" -o /opt/rt-n56u/trunk/user/v2ray/bin/v2ray; \
)
**/bin/sh: 5: go: Permission denied**
make[2]: *** [Makefile:30: build_v2ray] Error 127
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/v2ray'
make[1]: *** [Makefile:228: all] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
make: *** [Makefile:202: user_only] Error 2

**Comment by MSquach** [comment]
同求，麻烦大大说下。。。

**Comment by chongshengB** [comment]
是用root用户编译的么？

**Comment by MSquach** [comment]
是sudo build_firmware_modify xxx

**Comment by chongshengB** [comment]
建议切换到root用户编译，我在GitHub action和自己虚拟机测试均能正常编译

**Comment by MSquach** [comment]
我用sudo 去v2目录下单独编译能生成BIN。但用sudo build_firmxxxxxxxx 就会包go 的权限不足。。。

**Comment by MSquach** [comment]
用su    go直接提示没有这个命令

**Comment by BunnyYang05** [comment]
用 sudo fakeroot build_firmware... 尝试同样是这个结果

**Comment by Magic-Xin** [comment]
同样报错加一
编译环境是ubuntu 18.04 wsl，sudo -i进入root执行的 fakeroot ./build_firmware_modify RM2100

```
make[2]: Entering directory '/opt/rt-n56u/trunk/user/unblockmusic'
( if [ ! -f /opt/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusic-0.2.3.tar.gz ]; then \
curl --create-dirs -L https://github.com/cnsilvan/UnblockNeteaseMusic/archive/0.2.3.tar.gz -o /opt/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusic-0.2.3.tar.gz ; \
fi )
mkdir -p /opt/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusicGo
mkdir -p /opt/rt-n56u/trunk/user/unblockmusic/bin
( if [ ! -d /opt/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusicGo/UnblockNeteaseMusic-0.2.3 ]; then \
tar zxfv /opt/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusic-0.2.3.tar.gz -C /opt/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusicGo ; \
fi )
UnblockNeteaseMusic-0.2.3/
UnblockNeteaseMusic-0.2.3/LICENSE
UnblockNeteaseMusic-0.2.3/README.md
UnblockNeteaseMusic-0.2.3/app.go
UnblockNeteaseMusic-0.2.3/build.sh
UnblockNeteaseMusic-0.2.3/cache/
UnblockNeteaseMusic-0.2.3/cache/cache.go
UnblockNeteaseMusic-0.2.3/common/
UnblockNeteaseMusic-0.2.3/common/common.go
UnblockNeteaseMusic-0.2.3/config/
UnblockNeteaseMusic-0.2.3/config/config.go
UnblockNeteaseMusic-0.2.3/createCertificate.sh
UnblockNeteaseMusic-0.2.3/go.mod
UnblockNeteaseMusic-0.2.3/go.sum
UnblockNeteaseMusic-0.2.3/host/
UnblockNeteaseMusic-0.2.3/host/host.go
UnblockNeteaseMusic-0.2.3/network/
UnblockNeteaseMusic-0.2.3/network/network.go
UnblockNeteaseMusic-0.2.3/processor/
UnblockNeteaseMusic-0.2.3/processor/crypto/
UnblockNeteaseMusic-0.2.3/processor/crypto/crypto.go
UnblockNeteaseMusic-0.2.3/processor/processor.go
UnblockNeteaseMusic-0.2.3/provider/
UnblockNeteaseMusic-0.2.3/provider/kugou/
UnblockNeteaseMusic-0.2.3/provider/kugou/kugou.go
UnblockNeteaseMusic-0.2.3/provider/kuwo/
UnblockNeteaseMusic-0.2.3/provider/kuwo/kuwo.go
UnblockNeteaseMusic-0.2.3/provider/kuwo/kuwoDES.go
UnblockNeteaseMusic-0.2.3/provider/migu/
UnblockNeteaseMusic-0.2.3/provider/migu/migu.go
UnblockNeteaseMusic-0.2.3/provider/provider.go
UnblockNeteaseMusic-0.2.3/proxy/
UnblockNeteaseMusic-0.2.3/proxy/proxy.go
UnblockNeteaseMusic-0.2.3/utils/
UnblockNeteaseMusic-0.2.3/utils/utils.go
UnblockNeteaseMusic-0.2.3/version/
UnblockNeteaseMusic-0.2.3/version/version.go
( cd /opt/rt-n56u/trunk/user/unblockmusic/UnblockNeteaseMusicGo/UnblockNeteaseMusic-0.2.3; \
GOOS=linux GOARCH=mipsle go build -ldflags "-w -s" -o /opt/rt-n56u/trunk/user/unblockmusic/bin/UnblockNeteaseMusic; \
)
/bin/sh: 2: go: Permission denied
Makefile:17: recipe for target 'build' failed
make[2]: *** [build] Error 127
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/unblockmusic'
Makefile:228: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
Makefile:202: recipe for target 'user_only' failed
make: *** [user_only] Error 2
```

**Comment by MSquach** [comment]
就是go命令的环境变量没弄好，去查查就行

**Comment by CodeChenL** [comment]
我也出现了和你一样的错误，用root编译也不行

**Comment by epre5** [comment]
我也遇到了同样问题，解决方法是去[安装最新版go](https://golang.org/doc/install)，可以用go version看看是否正确安装。

**Comment by CodeChenL** [comment]
> 我也遇到了同样问题，解决方法是去[安装最新版go](https://golang.org/doc/install)，可以用go version看看是否正确安装。

真的可以哎, @chongshengB ,找到思路了,看看怎么加到源码的编译工具立吧

**Comment by Magic-Xin** [comment]
重装golang后已解决

**Comment by chongshengB** [comment]
已修复此问题~可同步最新源码测试
