### ISSUE TITLE
云音乐解锁的二进制选项不起作用

### ISSUE THREAD

**Issue by bash99** [chongshengB/rt-n56u#367]
CONFIG_FIRMWARE_INCLUDE_WYYBIN=n
CONFIG_FIRMWARE_INCLUDE_WYY=y

时，编译出来的固件里面仍然有那个2M多的二进制文件，然后固件就超过8M了。

看配置似乎在user/Makefile 只有CONFIG_FIRMWARE_INCLUDE_WYY的判断

**Comment by chongshengB** [comment]
此选项已取消，现在二进制文件必须编译进固件才能使用

**Comment by bash99** [comment]
不好意思再打扰一下，看配置界面里面还有用 网络代理的选项啊（比如阿里云北京什么的），这些也需要本地二进制吗？

**Comment by bash99** [comment]
实验了一下，在build时把trunk/user/unblockmusic/Makefile里面复制 二进制那行删除。

sed -i '/\usr\/bin\/UnblockNeteaseMusic/d' user/unblockmusic/Makefile

然后刷机是有脚本和界面的，虽然自带的几个公开服务器都有问题用不了，但是自己在局域网里面跑了一个 UnblockNeteaseMusic 后，可以正常启用解锁功能。

build文件
https://github.com/bash99/Padavan-build/blob/master/.github/workflows/build-padavan.yml
