### ISSUE TITLE
kernel: Replay Counter Different in group msg 2 of 2-way handshake!

### ISSUE THREAD

**Issue by biozzl** [chongshengB/rt-n56u#379]
AtuoBuild 496129e latest release.

Prompt multiple error message as below：
Aug  2 22:40:41 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  2 23:40:52 kernel: WPAHandshakeMsgRetryExec::Group rekey timeout from 54:14:73:9B:03:02
Aug  3 00:40:45 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 01:40:47 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 02:40:49 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 03:40:50 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 03:40:51 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 05:40:55 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 06:40:57 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 07:40:59 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  3 08:41:00 kernel: Replay Counter Different in group msg 2 of 2-way handshake!

**Comment by forever2019** [comment]
Aug  9 16:40:36 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  9 17:40:37 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  9 19:40:39 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
Aug  9 20:40:40 kernel: Replay Counter Different in group msg 2 of 2-way handshake!
我也出现了    RM2100    最新固件

**Comment by sd1561026** [comment]
我也发现这个报错了   是什么原因造成的呢 ？
