### ISSUE TITLE
JDC led状态

### ISSUE THREAD

**Issue by Vodomine** [chongshengB/rt-n56u#39]
感谢适配京东云，发现LED灯状态不对，
未联网红色，联网为蓝色，现在连上网是白色的，三色灯都亮了

gpio------12 蓝色 8 绿色

**Comment by chongshengB** [comment]
灯的适配是正常的，因为我自己也有这个设备，老毛子默认是打开了全部灯...类似于K2P。我可以研究下尽量接近官方的那种，你可以先在老毛子关闭你不需要的灯

**Comment by Vodomine** [comment]
对，灯是正常的，官方状态是断线红的，连上是蓝的，跟你这个不一样，可以优化一下，不改也没啥关系也不影响使用
