### ISSUE TITLE
如何使miniupnpd插件支持IGD V1

### ISSUE THREAD

**Issue by wang-jiajia** [chongshengB/rt-n56u#394]
现在的版本miniupnpd 只能支持IGD V2，对于有些不支持IGD V2的软件，比如一些国产软件，就无法建立upnp连接，请问如何实现支持IGD V1

**Comment by Ljzkirito** [comment]
你看看修改rt-n56u/trunk/user/miniupnpd/Makefile中13行
cd $(SRC_NAME) && ./genconfig.sh --ipv6 --igd2
改成
cd $(SRC_NAME) && ./genconfig.sh --ipv6
这样行不行

**Comment by wang-jiajia** [comment]
> 你看看修改rt-n56u/trunk/user/miniupnpd/Makefile中13行
> cd $(SRC_NAME) && ./genconfig.sh --ipv6 --igd2
> 改成
> cd $(SRC_NAME) && ./genconfig.sh --ipv6
> 这样行不行

感谢，这个方法是可行的
