### ISSUE TITLE
编译失败，有没有大佬帮我看看是哪里出错了

### ISSUE THREAD

**Issue by Hear1423** [chongshengB/rt-n56u#396]
hecking for ncurses/ncurses.h... no
checking ncurses/curses.h usability... no
checking ncurses/curses.h presence... no
checking for ncurses/curses.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating htop.1
config.status: creating config.h
config.status: executing depfiles commands
make[3]: 离开目录“/opt/rt-n56u/trunk/user/htop”
make -j8 -C htop-2.2.0
make[3]: 进入目录“/opt/rt-n56u/trunk/user/htop/htop-2.2.0”
./scripts/MakeHeader.py CategoriesPanel.c
./scripts/MakeHeader.py MainPanel.c
./scripts/MakeHeader.py DisplayOptionsPanel.c
./scripts/MakeHeader.py Header.c
./scripts/MakeHeader.py htop.c
/usr/bin/env: “python”: 没有那个文件或目录
make[3]: *** [Makefile:1416：CategoriesPanel.h] 错误 127
make[3]: *** 正在等待未完成的任务....
/usr/bin/env: “python”: 没有那个文件或目录
make[3]: *** [Makefile:1416：MainPanel.h] 错误 127
/usr/bin/env: “python”: 没有那个文件或目录
make[3]: *** [Makefile:1416：DisplayOptionsPanel.h] 错误 127
/usr/bin/env: “python”: 没有那个文件或目录
make[3]: *** [Makefile:1416：Header.h] 错误 127
/usr/bin/env: “python”: 没有那个文件或目录
make[3]: *** [Makefile:1416：htop.h] 错误 127
make[3]: 离开目录“/opt/rt-n56u/trunk/user/htop/htop-2.2.0”
make[2]: *** [Makefile:6：all] 错误 2
make[2]: 离开目录“/opt/rt-n56u/trunk/user/htop”
make[1]: *** [Makefile:213：all] 错误 2
make[1]: 离开目录“/opt/rt-n56u/trunk/user”
make: *** [Makefile:202：user_only] 错误 2
hear@hear-virtual-machine:/opt/rt-n56u/trunk$

**Comment by xiaole51** [comment]
很明显没装python.
编译说明的依赖包重新都安装一下.
