### ISSUE TITLE
科学上网V2RAY能否增加allowInsecure的选项

### ISSUE THREAD

**Issue by lizhanhong1988** [chongshengB/rt-n56u#45]
科学上网V2RAY能否增加allowInsecure的选项呢？

**Comment by ntgeralt** [comment]
我也说几点建议，您可以看看
iptables -t nat -A V2RAY -p tcp --dport 22:500 -j REDIRECT --to-ports 1234

16M flash如oye，yk-l1固件集成v2；适配小余C1/C5。
