### ISSUE TITLE
ss plus 无法使用。连上无法fq

### ISSUE THREAD

**Issue by sunyb3** [chongshengB/rt-n56u#5]
ss plus 无法使用。连上无法fq

**Comment by chongshengB** [comment]
用什么客户端？ss?ssr?v2ray?

**Comment by sunyb3** [comment]
> 用什么客户端？ss?ssr?v2ray?

ss，ssr，v2ray都连接不上，v2ray 感觉还有其他问题，域名+wss+tls这种的  域名会被转成ip 然后会连接不上
