### ISSUE TITLE
想问下smartdns的上游服务器有没有必要设置？以及配置文件保存在哪？

### ISSUE THREAD

**Issue by vvyoko** [chongshengB/rt-n56u#53]
请问配置文件里有自带的上游服务器吗？
翻了下只找到一个smartdns.conf相关的文件，其他的都是空的。
但是这里面没有设置上游服务器。
所以想问下有自带的上游服务器吗，有的话请问下配置文件在哪？
没有的话是需要自己手动添加上游服务器吗？

如果要设置的话请问在以下情况该怎么设置？
我在smartdns页面打开了 
加载ChnrouteIP为白名单 |
加载ChnrouteIP为黑名单 |
然后上游服务器页面是设置国内的DNS白名单，国外的DNS黑名单是吗？
请问按图片这样设置对吗？
![1](https://user-images.githubusercontent.com/2145741/74023235-23c48000-49da-11ea-97b9-9a7e655e67d2.jpg)
另外请问下设置完的配置文件保存在哪？
一个个设置完挺麻烦的，想保存配置文件下次刷机就不用重新手动设置了。

如果可能还是希望能自带上游服务器。
看来看去大家的设置都是差不多
223.5.5.5，180.76.76.76，119.29.29.29，8.8.8.8，8.8.4.4,1.1.1.1之类
为什么就不能自带一组上游服务器呢。
这个好像应该去smartdns那边反馈，但是那边好像见一个这样issues就锁一个，也不知道是什么态度。

**Comment by chongshengB** [comment]
以后会考虑增加默认方案供选择，其实每个人的宽带环境不一样，还是建议自己测试增加，配置文件在 /etc/storage/smartdns.conf ，感谢您的建议

**Comment by ntgeralt** [comment]
建议上游服务器分组，可选择这条dns只用于gfwlist解析。因为现在测试，国内dns的google污染解析依然会纳入结果。另外黑白名单我也玩不好，无法使用某条dns用于解析gfwlist

**Comment by chongshengB** [comment]
> 建议上游服务器分组，可选择这条dns只用于gfwlist解析。因为现在测试，国内dns的google污染解析依然会纳入结果。另外黑白名单我也玩不好，无法使用某条dns用于解析gfwlist

上游加入服务器组选项，再配合第二服务器，应该可以单独解析gfwlist，这个我后期加一下选项
目前我自己是国内的DNS加载白名单，暂时不会出现污染问题
