### ISSUE TITLE
K2P中VPN选项没有了

### ISSUE THREAD

**Issue by pdd083051** [chongshengB/rt-n56u#54]
K2P中VPN选项没有了，模板中说是移到了更多设置里面，但是连上网络之后，更多设置选项出不来了。

**Comment by yuaiwu** [comment]
修改state.js文件
//Level 1 Menu in Gateway, Router mode
menuL1_title = new Array("", "<#menu1#>", "<#menu3#>", "<#menu2#>", "<#menu6#>", "<#menu4#>", "<#menu5_8#>", "<#menu5#>");
menuL1_link = new Array("", "index.asp", "aidisk.asp", "vpnsrv.asp", "vpncli.asp", "Main_TrafficMonitor_realtime.asp", "Advanced_System_Info.asp", "as.asp");

**Comment by shine1000** [comment]
请问楼上，state.js这文件在哪目录下 @yuaiwu

**Comment by shine1000** [comment]
> K2P中VPN选项没有了，模板中说是移到了更多设置里面，但是连上网络之后，更多设置选项出不来了。

兄弟 你这个问题解决了没   分享下

**Comment by pdd083051** [comment]
> > K2P中VPN选项没有了，模板中说是移到了更多设置里面，但是连上网络之后，更多设置选项出不来了。
> 
> 兄弟 你这个问题解决了没 分享下

没有，需要修改代码了，暂时我也用不着，本来编译了带FRP的，固件过大了，算了，现在就看稳定性好就行了。

**Comment by yuaiwu** [comment]
state.js文件位置在：/opt/rt-n56u/trunk/user/www/n56u_ribbon_fixed/
请搜索一下不就有了。
