### ISSUE TITLE
使用trojan上网时进GFW模式正常

### ISSUE THREAD

**Issue by BlackJackonGH** [chongshengB/rt-n56u#541]
最近使用trojan上网，发现仅GFW模式能正常使用，绕过大陆ip及全局模式都不正常。

**Comment by zilijing** [comment]
设置一下sock5

**Comment by BlackJackonGH** [comment]
> 设置一下sock5

你好，能说说具体怎么设置吗？我目前的情况是GFW模式访问被墙网址正常，绕过模式访问外网没被墙的网址正常。另外我将socks5设置成与主服务器相同，完了绕过模式下外网都无法访问。

**Comment by BlackJackonGH** [comment]
在客户端设置里将“加载Chinadns-ng(仅绕过模式生效)”打开即可正常使用。
