### ISSUE TITLE
koolproxy 规则自动更新时间 无法设置

### ISSUE THREAD

**Issue by yuaiwu** [chongshengB/rt-n56u#57]
koolproxy 规则自动更新时间 无法设置（无下拉箭头，也无法填写数值）

**Comment by chongshengB** [comment]
可以吧？你再试试？

**Comment by yuaiwu** [comment]
输入时数值，按“应用设置”，数值自动恢复成默认值：3

**Comment by yuaiwu** [comment]
建议variables.c文件添加一行{"koolproxy_update_hour", "", NULL, EVM_RESTART_KOOLPROXY},
顺便state.js文件修改一下L1_title = new Array（“”，“ <＃menu1＃>”，“ <＃menu3＃>”，“ <＃menu2＃>”，“ <＃ menu6＃>”，“ <＃menu4＃>”，“ <＃menu5_8＃>”，“ <＃menu5＃>”）；
menuL1_link = new Array（“”，“ index.asp”，“ aidisk.asp”，“ vpnsrv.asp”，“ vpncli.asp”，“ Main_TrafficMonitor_realtime.asp”，“ Advanced_System_Info.asp”，“ as.asp”） ;
