### ISSUE TITLE
k2p改usb问题

### ISSUE THREAD

**Issue by uancan** [chongshengB/rt-n56u#63]
k2p改了usb，刷那个k2p-usb固件，breed web 恢复控制台固件大小超过了15.69 MB。。。。刷k2p固件又不能挂载usb。。。。怎么办

**Comment by dabster163** [comment]
硬改32m

**Comment by yuaiwu** [comment]
自定义编译吧

[K2P_3.4.3.9-099.zip](https://github.com/chongshengB/rt-n56u/files/4211683/K2P_3.4.3.9-099.zip)
