### ISSUE TITLE
ShadowSocksR Plus+似乎还是有些问题

### ISSUE THREAD

**Issue by icy37785** [chongshengB/rt-n56u#7]
我在使用ssr的过程中没办法正常使用，打开网页会提示“建立安全连接失败”
我使用的算法是chacha20-ietf，协议是auth_sha1_v4，混淆是tls1.2_ticket_auth。
然后我使用v2ray可以正常使用，有的时候会卡顿，我看日志发现v2ray每5分钟会重启一次，v2ray启动需要一点时间，所以偶尔会卡顿，我猜测这个重启是客户端的保活，但是保活的逻辑可不可以不用整个重启而是检查进程或是怎么样呢。

**Comment by chongshengB** [comment]
感谢反馈，我修复一下

**Comment by chongshengB** [comment]
已修复
