### ISSUE TITLE
希望能增加 RT-N56UB1-M1-512M_3.4.3.9-099

### ISSUE THREAD

**Issue by cutepan** [chongshengB/rt-n56u#71]
我一直都刷hiboyhiboyhiboy的固件
他里面有这个RT-N56UB1-M1-512M_3.4.3.9-099
望能添加上这个固件的更新！！谢谢！
https://opt.cn2qq.com/padavan/

**Comment by chongshengB** [comment]
我能找到这个机型的配置文件就加吧
