### ISSUE TITLE
在某些情况下系统管理打不开

### ISSUE THREAD

**Issue by xiaoguaishou92** [chongshengB/rt-n56u#74]
我开启桥接和v2ray之后，系统管理页面就进不去了。尝试关闭和清楚日志之后依然不行

**Comment by chongshengB** [comment]
不用桥接模式会么？你用哪种桥接方式？

**Comment by xiaoguaishou92** [comment]
我大概重试了一些，我如果刷机后恢复出厂在配置桥接模式才会出这个问题  机型是斐讯k2

**Comment by chongshengB** [comment]
是桥接模式不是切换了路由为ap模式吧？

**Comment by jelly0925** [comment]
我刷的k2p-usb 20200226版本后，只要开启了无线桥接模式以后，就打不开网络信息页面了，在没有开启桥接功能之前网络信息页面显示是正常的，希望下个版本可以修复一下呀。
