### ISSUE TITLE
Ubuntu18.04编译酸酸乳出现错误，求大神指点谢谢~

### ISSUE THREAD

**Issue by kevin2zhu** [chongshengB/rt-n56u#78]
/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/lib/gcc/mipsel-linux-uclibc/7.4.0/../../../../mipsel-linux-uclibc/bin/ld: ss_local-udprelay.o: in function `create_remote_socket':
/opt/rt-n56u/trunk/user/shadowsocks/shadowsocksr-libev-master/src/udprelay.c:363: undefined reference to `in6addr_any'
collect2: error: ld returned 1 exit status
编译环境:Ubuntu18.04、内核:5.3.0-41-generic GCC版本：gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
适配路由配置文件:K2P_nano.config ,未开启ss和IPV6的支持。

**Comment by chongshengB** [comment]
是不是未完全关闭ss选项？

**Comment by kevin2zhu** [comment]
感谢回复，我重新弄了一遍环境。这次也不知咋地就编成功了。
