### ISSUE TITLE
PSG1218编译的固件无法cifs加载SMB共享！请大神指教！

### ISSUE THREAD

**Issue by g0g001** [chongshengB/rt-n56u#82]
请问K2想挂载SMB，出现如下情况，是什么问题？
PSG1218:/home/root # mkdir -p /media/cifs
PSG1218:/home/root # mount -t cifs //192.168.2.253/K2 /media/cifs -o username=root,password=******,dynperm,nounix,noserverino,file_mode=0777,dir_mode=0777
mount: mounting //192.168.2.253/K2 on /media/cifs failed: No such device

我编译固件的  .config 如下：https://github.com/g0g001/xiazai/blob/master/PSG1218.config

同样的命令，刷H大的固件，就能挂载。排除了SMB共享的问题。
麻烦知道原因的大神不吝指教。

**Comment by chongshengB** [comment]
可能是内核没有编译这个文件系统

**Comment by g0g001** [comment]
请问如何才能编译出带cifs功能的固件？
