### ISSUE TITLE
AdguardHome not Work.

### ISSUE THREAD

**Issue by ag2s20150909** [chongshengB/rt-n56u#85]
`系统日志里面显示：AdGuardHome: 运行AdGuardHome
但在WEBUI里面无法打开WEB管理地址: http://192.168.2.1:3030
浏览器报错：ERR_CONNECTION_REFUSED

**Comment by chongshengB** [comment]
可能是下载失败，建议看看进程有无运行

**Comment by ag2s20150909** [comment]
> 可能是下载失败，建议看看进程有无运行

系统日志如下，型号360P2
Mar  1 20:08:52 AdGuardHome: 下载AdGuardHome
Mar  1 20:15:37 AdGuardHome: AdGuardHome下载成功。
Mar  1 20:15:37 AdGuardHome: 运行AdGuardHome

**Comment by izhangzhihao** [comment]
能否将AdGuardHome的二进制文件打包到固件中，这样就不需要每次启动的时候去下载了
