### ISSUE TITLE
为什么我编译的PSG1218固件，连wget命令都有问题？？？

### ISSUE THREAD

**Issue by g0g001** [chongshengB/rt-n56u#92]
PSG1218:/home/root # wget http://www.baidu.com
Connecting to www.baidu.com (180.101.49.41:80)
index.html           100% |**********************************|  2381   0:00:00 ETA
PSG1218:/home/root # wget https://www.baidu.com
Connecting to www.baidu.com (180.101.49.41:443)
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
PSG1218:/home/root # wget https://www.baidu.com --no-check-certificate
Connecting to www.baidu.com (180.101.49.42:443)
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
PSG1218:/home/root # wget --no-check-certificate https://www.baidu.com
Connecting to www.baidu.com (180.101.49.42:443)
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
PSG1218:/home/root #

**Comment by g0g001** [comment]
> PSG1218:/home/root # wget http://www.baidu.com
> Connecting to [www.baidu.com](http://www.baidu.com) (180.101.49.41:80)
> index.html 100% |**********************************| 2381 0:00:00 ETA
> PSG1218:/home/root # wget https://www.baidu.com
> Connecting to [www.baidu.com](http://www.baidu.com) (180.101.49.41:443)
> wget: can't execute 'openssl': No such file or directory
> wget: error getting response: Connection reset by peer
> PSG1218:/home/root # wget https://www.baidu.com --no-check-certificate
> Connecting to [www.baidu.com](http://www.baidu.com) (180.101.49.42:443)
> wget: can't execute 'openssl': No such file or directory
> wget: error getting response: Connection reset by peer
> PSG1218:/home/root # wget --no-check-certificate https://www.baidu.com
> Connecting to [www.baidu.com](http://www.baidu.com) (180.101.49.42:443)
> wget: can't execute 'openssl': No such file or directory
> wget: error getting response: Connection reset by peer
> PSG1218:/home/root #

https的链接无法下载！！！！！

**Comment by g0g001** [comment]
难道只有我编译的固件有问题！！！

**Comment by texchan** [comment]
你这应该是没去配置文件里开openssl，默认是关闭的

**Comment by g0g001** [comment]
> 你这应该是没去配置文件里开openssl，默认是关闭的

谢谢你的答案，已解决。
