### ISSUE TITLE
K2P SSR V2 UDP代理开启无效

### ISSUE THREAD

**Issue by luowei729** [chongshengB/rt-n56u#97]
K2P SSR V2 UDP代理开启无效

**Comment by luowei729** [comment]
kernel: x_tables: ip_tables: TPROXY target: only valid in mangle table, not nat

**Comment by ntgeralt** [comment]
是的，hiboy的ss udp转发，能让PS4变成NAT2。但楼主固件测试不行。
另外楼主你最新固件adbyby，手机的谷歌广告无法去掉。之前2月初的固件去广告反而能去掉所有谷歌广告。
